# Generated by Django 5.0.2 on 2024-04-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livekitsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='active_participants',
            field=models.ManyToManyField(related_name='active_livekit_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livekit_session', to='video.livekitroom'),
        ),
    ]
