# Generated by Django 5.0.2 on 2024-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_livekitsession_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivekitWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='livekitsession',
            name='active_participants',
        ),
        migrations.RemoveField(
            model_name='livekitsession',
            name='events',
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='both_have_been_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='u1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='u2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='webhook_events',
            field=models.ManyToManyField(related_name='livekit_session', to='video.livekitwebhookevent'),
        ),
    ]
