# Generated by Django 5.0.2 on 2024-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_livekitwebhookevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livekitsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
