# Generated by Django 5.0.2 on 2024-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_livekitsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='livekitsession',
            name='u1_was_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livekitsession',
            name='u2_was_active',
            field=models.BooleanField(default=False),
        ),
    ]
