# Generated by Django 5.0.3 on 2025-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_livekitsession_first_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livekitsession',
            name='unusual_length',
            field=models.BooleanField(default=False),
        ),
    ]
