# Generated by Django 5.0.3 on 2025-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_randomcalllobby_randomcallmatchings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomcallmatchings',
            name='followUpMatchFlag',
        ),
        migrations.RemoveField(
            model_name='randomcallmatchings',
            name='reportedFlag',
        ),
        migrations.AddField(
            model_name='randomcallmatchings',
            name='follow_up_match_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomcallmatchings',
            name='reported_flag',
            field=models.BooleanField(default=False),
        ),
    ]
