# Generated by Django 5.0.3 on 2025-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_livekitsession_unusual_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='livekitsession',
            name='start_end_before_correction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
