# Generated by Django 5.0.3 on 2025-11-17 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_livekitsession_start_end_before_correction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCallLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RandomCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('random_match', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reported_flag', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('tmp_chat', models.CharField(max_length=50)),
                ('tmp_match', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livekitroom',
            name='random_call_room',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RandomCallLobbyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_users', to='video.randomcalllobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_lobby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RandomCallMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('u1_accepted', models.BooleanField(default=False)),
                ('u2_accepted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('in_session', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_matchings', to='video.randomcalllobby')),
                ('u1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u1_randomcall_session', to=settings.AUTH_USER_MODEL)),
                ('u2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2_randomcall_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
