# Generated by Django 5.0.3 on 2025-06-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messageattachment_message_attachments'),
        ('video', '0008_remove_randomcallmatchings_followupmatchflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatchings',
            name='tmp_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_chat', to='chat.chat'),
            preserve_default=False,
        ),
    ]
