# Generated by Django 5.0.3 on 2025-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_randomcalllobby_randomcallsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcalllobbyuser',
            name='last_status_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
