# Generated by Django 5.0.3 on 2025-07-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_randomcallmatchings_tmp_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomcallmatchings',
            name='tmp_chat',
            field=models.CharField(max_length=50),
        ),
    ]
