# Generated by Django 5.0.3 on 2025-11-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_randomcalllobbyuser_last_status_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
