# Generated by Django 5.0.3 on 2025-07-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_randomcallmatchings_tmp_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatchings',
            name='tmp_match',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
