# Generated by Django 5.0.3 on 2025-07-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_randomcallmatchings_tmp_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatchings',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
