# Generated by Django 5.0.3 on 2025-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_randomcallmatching_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='u1_matching_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomcallmatching',
            name='u2_matching_requested',
            field=models.BooleanField(default=False),
        ),
    ]
