# Generated by Django 5.0.3 on 2025-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_randomcallmatching_u1_matching_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcalllobby',
            name='match_proposal_timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='randomcalllobby',
            name='user_online_state_timeout',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='randomcalllobby',
            name='video_call_timeout',
            field=models.IntegerField(default=600),
        ),
    ]
