# Generated by Django 5.0.3 on 2025-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_randomcalllobby_match_proposal_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
