# Generated by Django 5.0.3 on 2025-07-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_randomcallsession_randomcallmatching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
