# Generated by Django 5.0.3 on 2025-11-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_randomcallmatching_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='u1_requested_room_token',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomcallmatching',
            name='u2_requested_room_token',
            field=models.BooleanField(default=False),
        ),
    ]
