# Generated by Django 5.0.3 on 2025-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_randomcallmatching_u1_requested_room_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='both_requested_room_token',
            field=models.BooleanField(default=False),
        ),
    ]
