# Generated by Django 5.1.15 on 2026-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_randomcallmatching_both_requested_room_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='u1_confirmed_rejection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomcallmatching',
            name='u2_confirmed_rejection',
            field=models.BooleanField(default=False),
        ),
    ]
