# Generated by Django 5.1.15 on 2026-02-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_randomcallmatching_u1_confirmed_rejection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='both_confirmed_rejection',
            field=models.BooleanField(default=False),
        ),
    ]
