# Generated by Django 5.1.15 on 2026-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_randomcallmatching_both_confirmed_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
