# Generated by Django 5.1.15 on 2026-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_randomcallmatching_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcalllobby',
            name='match_rejection_confirmation_timeout',
            field=models.IntegerField(default=10),
        ),
    ]
