# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_randomcallmatching_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='confirmed_match',
            field=models.BooleanField(default=False),
        ),
    ]
