# Generated by Django 5.1.15 on 2026-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_randomcallmatching_confirmed_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
