# Generated by Django 5.1.15 on 2026-04-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_randomcallmatching_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
