# Generated by Django 5.1.15 on 2026-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_randomcallmatching_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcalllobby',
            name='match_accept_timeout',
            field=models.IntegerField(default=30),
        ),
    ]
