# Generated by Django 5.1.15 on 2026-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_randomcalllobby_match_accept_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcallmatching',
            name='vido_call_join_expired',
            field=models.BooleanField(default=False),
        ),
    ]
