# Generated by Django 5.1.15 on 2026-04-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_randomcallmatching_vido_call_join_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomcallmatching',
            old_name='vido_call_join_expired',
            new_name='video_call_join_expired',
        ),
    ]
