FROM python:3.10-alpine

WORKDIR /back

COPY ./requirements.txt ./

# psycopg2-binary is fufficient for DB acess
# But if we want `manage.py dbshell` might might need some more stuff:
# RUN apk add libpq-dev python3-dev
# RUN apk add postgres
RUN pip install --no-cache-dir -r requirements.txt
RUN pip cache purge

EXPOSE 8000

# Required for extracting translations strings
RUN apk add gettext
RUN apk add --update --no-cache py3-numpy
# link the numpy installation
ENV PYTHONPATH=/usr/lib/python3.10/site-packages

# Would have went with daphne but no hot reloading (https://github.com/django/daphne/issues/9) is quire problematic
CMD ["sh", "./entry.sh"]