FROM python:3.10-alpine

WORKDIR /back

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN pip cache purge

EXPOSE 8000

# Required for extracting translations strings
RUN apk add gettext

# Would have went with daphne but no hot reloading (https://github.com/django/daphne/issues/9) is quire problematic
CMD ["sh", "./entry.sh"]