FROM python:3.11-alpine

WORKDIR /back

COPY ./requirements.txt ./

# psycopg2-binary is fufficient for DB acess
# But if we want `manage.py dbshell` might might need some more stuff:
# RUN apk add libpq-dev python3-dev
# RUN apk add postgres
RUN pip install --no-cache-dir -r requirements.txt
RUN apk add --no-cache git
RUN pip install git+https://github.com/jazzband/django-revproxy.git
RUN pip cache purge

EXPOSE 8000

# Required for extracting translations strings
RUN apk add gettext
RUN apk add --update --no-cache py3-numpy
# link the numpy installation
ENV PYTHONPATH="/usr/lib/python3.11/site-packages/:${PYTHONPATH}"

# Would have went with daphne but no hot reloading (https://github.com/django/daphne/issues/9) is quire problematic
CMD ["sh", "./entry.sh"]