from django.db import models
from .user import User


class MatchinScores(models.Model):
    """
    This model hols scores for *every* person to *every* person.
    So this basicly contains the eges for a directed graph.
    There should always exist an egde between every two users.

    This is updated everytime a user changes his matching form
    """
    from_usr = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="from_usr")

    to_usr = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="to_usr")

    """
    We add this extra relation slug it tells us for which direction this score is 
    it is always formated as <from-hash>_<to-hash>
    """
    relation_slug = models.CharField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    score = models.IntegerField()  # The raw score value!
    messages = models.JSONField()  # The messages generated by the matching algo
    matchable = models.BooleanField()  # If these two are matchable

    meta = models.JSONField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['from_usr', 'to_usr', 'relation_slug'], name='unique_from_to_usr_relation'
            )
        ]
