# Generated by Django 5.0.2 on 2024-03-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_notified',
            field=models.BooleanField(default=False),
        ),
    ]
