# Generated by Django 5.0.3 on 2024-12-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagebroadcastlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageBroadcastList',
        ),
    ]
