# Generated by Django 5.0.3 on 2025-01-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_chat_messag_sender__941e05_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parsable_message',
            field=models.BooleanField(default=False),
        ),
    ]
