# Generated by Django 5.0.3 on 2025-09-10 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_messageattachment_message_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['-created'], name='chat_created_desc'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['u1', 'u2'], name='chat_u1_u2'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['u2', 'u1'], name='chat_u2_u1'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat'], name='msg_chat_only'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created'], name='msg_chat_created_desc'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'recipient', 'read'], name='msg_chat_rec_read'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('read', False)), fields=['chat', 'recipient', '-created'], name='msg_unread_chat_rec_created'),
        ),
    ]
