# Generated by Django 5.0.3 on 2025-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_chat_created_desc_chat_chat_u1_u2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_random_call_chat',
            field=models.BooleanField(default=False),
        ),
    ]
