# Generated by Django 5.0.3 on 2026-01-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_is_random_call_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_random_call_chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='seven_days_inactive_email_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='three_days_inactive_email_send',
            field=models.BooleanField(default=False),
        ),
    ]
