# Generated by Django 5.0.3 on 2025-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chat_three_days_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seven_days_inactive',
            field=models.BooleanField(default=False),
        ),
    ]
