# Generated by Django 4.1.2 on 2022-11-12 15:21

from django.db import migrations, models
import tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=tracking.models._double_uuid, max_length=255, unique=True)),
                ('tags', models.JSONField()),
                ('func', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
            ],
        ),
    ]
