# Generated by Django 4.1.2 on 2022-12-01 01:09

import back.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=255, unique=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('misc', 'Misc event'), ('request', 'Request event'), ('database', 'Database event'), ('admin', 'Admin event'), ('flow', 'Flow event'), ('email', 'Email event'), ('front', 'Frontend event')], default='misc', max_length=255)),
                ('func', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
