# Generated by Django 4.1.2 on 2022-11-13 01:19

import back.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=255, unique=True)),
                ('tags', models.JSONField()),
                ('type', models.IntegerField(choices=[(0, 'Misc event'), (1, 'Request event'), (2, 'Database event'), (3, 'Admin event'), (4, 'Flow event'), (5, 'Email event'), (6, 'Frontend event')])),
                ('func', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
