# Generated by Django 4.1.2 on 2022-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True),
        ),
    ]
