# Generated by Django 4.1.2 on 2022-11-12 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='caller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(0, 'Misc event'), (1, 'Request event'), (2, 'Database event'), (3, 'Admin event'), (4, 'Flow event'), (5, 'Email event'), (6, 'Frontend event')], default=0),
            preserve_default=False,
        ),
    ]
