# Generated by Django 4.1.2 on 2022-12-14 00:18

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=255)),
                ('rate', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=1000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('summary_table', models.TextField()),
                ('meta', models.JSONField()),
            ],
        ),
    ]
