# Generated by Django 4.1.2 on 2023-01-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_summaries_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaries',
            name='summary_table',
        ),
    ]
