# Generated by Django 4.1.2 on 2023-02-19 13:19

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_summaries_summary_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=255)),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=255)),
                ('graph_data', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
