# Generated by Django 4.1.2 on 2023-02-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_graphmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphmodel',
            name='type',
            field=models.CharField(default='plot', max_length=255),
        ),
    ]
