# Generated by Django 5.1.15 on 2026-05-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0006_graphmodel_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionEventLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_name", models.CharField(max_length=100)),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="conversioneventlog",
            index=models.Index(fields=["event_name"], name="tracking_co_event_n_0897f6_idx"),
        ),
        migrations.AddIndex(
            model_name="conversioneventlog",
            index=models.Index(fields=["event_id"], name="tracking_co_event_i_0296ef_idx"),
        ),
        migrations.AddIndex(
            model_name="conversioneventlog",
            index=models.Index(fields=["sent_at"], name="tracking_co_sent_at_8474f5_idx"),
        ),
    ]
