# Generated by Django 5.1.15 on 2026-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_conversioneventlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversioneventlog',
            new_name='tracking_co_event_n_3c6142_idx',
            old_name='tracking_co_event_n_0897f6_idx',
        ),
        migrations.RenameIndex(
            model_name='conversioneventlog',
            new_name='tracking_co_event_i_be9b54_idx',
            old_name='tracking_co_event_i_0296ef_idx',
        ),
        migrations.RenameIndex(
            model_name='conversioneventlog',
            new_name='tracking_co_sent_at_132f4a_idx',
            old_name='tracking_co_sent_at_8474f5_idx',
        ),
    ]
