# Generated by Django 4.1.2 on 2023-05-23 14:21

from django.db import migrations, models
from management.models.settings import create_email_settings
import django


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20230523_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email_settings',
            field=models.OneToOneField(default=create_email_settings,on_delete=django.db.models.deletion.CASCADE, to='management.emailsettings', unique=True, null=False),
        ),
    ]
