# Generated by Django 4.1.2 on 2023-06-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='active',
        ),
    ]
