# Generated by Django 4.1.2 on 2023-07-17 15:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_match_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_verification_reminder1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='user_form_unfinished_reminder1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='user_form_unfinished_reminder2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='unsubscibed_options',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('interview_requests', 'Interview Requests'), ('survery_requests', 'Survery Requests'), ('finish_reminders', 'Finish Reminders')], default=[], max_length=500),
        ),
    ]
