# Generated by Django 5.0.3 on 2024-09-24 15:22

import management.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatenmatchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, validators=[management.validators.model_validate_first_name])),
                ('last_name', models.CharField(max_length=150, validators=[management.validators.model_validate_second_name])),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=50)),
                ('support_for', models.CharField(choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolecent', 'patenmatch.supportgroups.adolecent'), ('student', 'patenmatch.supportgroups.student')], default='individual', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatenmatchOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('contact_first_name', models.CharField(max_length=150, validators=[management.validators.model_validate_first_name])),
                ('contact_second_name', models.CharField(max_length=150, validators=[management.validators.model_validate_second_name])),
                ('contact_email', models.EmailField(max_length=50)),
                ('contact_phone', models.CharField(blank=True, max_length=255)),
                ('maximum_distance', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(blank=True, default=3)),
                ('target_groups', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolecent', 'patenmatch.supportgroups.adolecent'), ('student', 'patenmatch.supportgroups.student')], max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=1024)),
                ('website_url', models.URLField(blank=True, max_length=1024)),
                ('metadata', models.JSONField(blank=True)),
                ('matched_users', models.ManyToManyField(blank=True, to='patenmatch.patenmatchuser')),
            ],
        ),
    ]
