# Generated by Django 5.0.3 on 2024-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='maximum_distance',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='metadata',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='target_groups',
            field=models.CharField(blank=True, choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolecent', 'patenmatch.supportgroups.adolecent'), ('student', 'patenmatch.supportgroups.student')], max_length=255),
        ),
    ]
