# Generated by Django 5.0.3 on 2024-09-24 19:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0002_alter_patenmatchorganization_maximum_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolecent', 'patenmatch.supportgroups.adolecent'), ('student', 'patenmatch.supportgroups.student')], max_length=255),
        ),
    ]
