# Generated by Django 5.0.3 on 2024-11-06 11:38

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0003_alter_patenmatchorganization_target_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolescent', 'patenmatch.supportgroups.adolescent'), ('student', 'patenmatch.supportgroups.student')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patenmatchuser',
            name='support_for',
            field=models.CharField(choices=[('family', 'patenmatch.supportgroups.family'), ('child', 'patenmatch.supportgroups.child'), ('senior', 'patenmatch.supportgroups.senior'), ('individual', 'patenmatch.supportgroups.individual'), ('adolescent', 'patenmatch.supportgroups.adolescent'), ('student', 'patenmatch.supportgroups.student')], default='individual', max_length=255),
        ),
    ]
