# Generated by Django 5.0.3 on 2024-11-19 12:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0004_alter_patenmatchorganization_target_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='contact_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='postal_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', 'Familie'), ('child', 'Kinder (bis 12 Jahre)'), ('senior', 'Senioren'), ('individual', 'Individuell (Erwachsene)'), ('adolescent', 'Jugendliche (13-17 Jahre)'), ('student', 'Studierende')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patenmatchuser',
            name='support_for',
            field=models.CharField(choices=[('family', 'Familie'), ('child', 'Kinder (bis 12 Jahre)'), ('senior', 'Senioren'), ('individual', 'Individuell (Erwachsene)'), ('adolescent', 'Jugendliche (13-17 Jahre)'), ('student', 'Studierende')], default='individual', max_length=255),
        ),
    ]
