# Generated by Django 5.0.3 on 2024-11-28 15:19

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0005_alter_patenmatchorganization_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patenmatchuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('family', 'Familie'), ('child', 'Kinder (bis 12 Jahre)'), ('senior', 'Senioren'), ('individual', 'Individuell (Erwachsene)'), ('adolescent', 'Jugendliche (13-17 Jahre)'), ('student', 'Studierende'), ('error', 'patenmatch.supportgroups.error')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patenmatchuser',
            name='support_for',
            field=models.CharField(choices=[('family', 'Familie'), ('child', 'Kinder (bis 12 Jahre)'), ('senior', 'Senioren'), ('individual', 'Individuell (Erwachsene)'), ('adolescent', 'Jugendliche (13-17 Jahre)'), ('student', 'Studierende'), ('error', 'patenmatch.supportgroups.error')], default='individual', max_length=255),
        ),
    ]
