# Generated by Django 5.0.3 on 2024-12-11 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0006_patenmatchuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patenmatchuser',
            name='email_auth_hash',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='patenmatchuser',
            name='email_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatenmatchOrganizationUserMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patenmatch.patenmatchorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patenmatch.patenmatchuser')),
            ],
        ),
    ]
