# Generated by Django 5.0.3 on 2024-11-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0006_alter_patenmatchorganization_target_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganization',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
