# Generated by Django 5.0.3 on 2024-12-11 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0007_patenmatchuser_email_auth_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patenmatchorganization',
            name='status_access_token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='patenmatchuser',
            name='status_access_token',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
