# Generated by Django 5.0.3 on 2024-12-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0008_patenmatchorganization_status_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patenmatchuser',
            name='request_specific_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patenmatch.patenmatchorganization'),
        ),
    ]
