# Generated by Django 5.0.3 on 2024-12-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0009_patenmatchuser_request_specific_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='patenmatchuser',
            name='spoken_languages',
            field=models.TextField(blank=True),
        ),
    ]
