# Generated by Django 5.0.3 on 2024-12-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0011_patenmatchuser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchuser',
            name='request_specific_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_users', to='patenmatch.patenmatchorganization'),
        ),
    ]
