# Generated by Django 5.0.3 on 2025-02-04 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patenmatch', '0012_alter_patenmatchuser_request_specific_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenmatchorganizationusermatching',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patenmatch.patenmatchorganization'),
        ),
        migrations.AlterField(
            model_name='patenmatchorganizationusermatching',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patenmatch.patenmatchuser'),
        ),
    ]
