# Generated by Django 4.1.2 on 2022-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='failure',
            field=models.BooleanField(default=False),
        ),
    ]
