# Generated by Django 5.0.2 on 2024-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='log_version',
            field=models.IntegerField(default=0),
        ),
    ]
