# Generated by Django 4.1.2 on 2022-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='template',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
