# Generated by Django 5.0.2 on 2024-07-30 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emaillog_log_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('template', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('category_id', models.CharField(default='dynamic', max_length=255)),
                ('sender_id', models.CharField(default='noreply', max_length=255)),
            ],
        ),
    ]
