# Generated by Django 4.1.2 on 2022-11-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emaillog_failure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='failure',
            new_name='sucess',
        ),
    ]
