# Generated by Django 5.0.3 on 2024-09-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_dynamictemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplate',
            name='content',
            field=models.JSONField(default={}),
        ),
    ]
