# Generated by Django 5.0.3 on 2024-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_alter_dynamictemplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictemplate',
            name='theme',
            field=models.CharField(choices=[('little_world', 'little_world'), ('patenmatch', 'patenmatch')], default='little_world', max_length=255),
        ),
    ]
