# Generated by Django 5.1.15 on 2026-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_dynamictemplate_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='is_dyanmic_email',
            field=models.BooleanField(default=False),
        ),
    ]
