# Generated by Django 4.1.2 on 2022-11-17 15:00

import back.utils
import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.models.profile
import management.validators
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_read', models.DateTimeField(null=True)),
                ('state', models.IntegerField(choices=[(0, 'unread'), (1, 'read'), (2, 'archived')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'match'), (2, 'message')], default=0)),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.TextField(default='no-description')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_form_page', models.IntegerField(default=0)),
                ('user_form_state', models.IntegerField(choices=[(0, 'Unfilled user form'), (1, 'Filled user form')], default=0)),
                ('email_auth_hash', models.CharField(default=back.utils._double_uuid, max_length=255)),
                ('email_auth_pin', models.IntegerField(default=back.utils._rand_int6)),
                ('email_authenticated', models.BooleanField(default=False)),
                ('unread_message_count', models.IntegerField(default=0)),
                ('unread_message_count_update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user_category', models.IntegerField(choices=[(0, 'Undefined (user-c)'), (1, 'Spam (user-c)'), (2, 'Legit (user-c)'), (3, 'Test (user-c)')], default=0)),
                ('matches', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notifications', models.ManyToManyField(blank=True, related_name='n+', to='management.notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAtMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=None, max_length=150, validators=[management.validators.validate_name])),
                ('second_name', models.CharField(default=None, max_length=150, validators=[management.validators.validate_name])),
                ('user_type', models.IntegerField(choices=[(0, 'Volunteer'), (1, 'Language learner')], default=0)),
                ('past_user_types', models.JSONField(blank=True, null=True)),
                ('target_group', models.IntegerField(choices=[(0, 'Any Group'), (1, 'Refugees only'), (2, 'Students only'), (3, 'Workers only')], default=0)),
                ('partner_sex', models.IntegerField(choices=[(0, 'Any sex'), (1, 'Male only'), (2, 'Female only')], default=0)),
                ('speech_medium', models.IntegerField(choices=[(0, 'Any medium'), (1, 'Video only'), (2, 'Phone only')], default=0)),
                ('partner_location', models.IntegerField(choices=[(0, 'Location Anywhere'), (1, 'Location close'), (2, 'Location far')], default=0)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('liability', models.IntegerField(choices=[(0, 'Declined Liability'), (1, 'Accepted Liability')], default=0)),
                ('notify_channel', models.IntegerField(choices=[(0, 'Notify per email'), (1, 'Notify per SMS'), (2, 'Notify by calling')], default=2)),
                ('phone_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('sdate', models.CharField(default=management.models.profile._date_string, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=None, max_length=150, validators=[management.validators.validate_name])),
                ('second_name', models.CharField(default=None, max_length=150, validators=[management.validators.validate_name])),
                ('user_type', models.IntegerField(choices=[(0, 'Volunteer'), (1, 'Language learner')], default=0)),
                ('past_user_types', models.JSONField(blank=True, null=True)),
                ('target_group', models.IntegerField(choices=[(0, 'Any Group'), (1, 'Refugees only'), (2, 'Students only'), (3, 'Workers only')], default=0)),
                ('partner_sex', models.IntegerField(choices=[(0, 'Any sex'), (1, 'Male only'), (2, 'Female only')], default=0)),
                ('speech_medium', models.IntegerField(choices=[(0, 'Any medium'), (1, 'Video only'), (2, 'Phone only')], default=0)),
                ('partner_location', models.IntegerField(choices=[(0, 'Location Anywhere'), (1, 'Location close'), (2, 'Location far')], default=0)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('liability', models.IntegerField(choices=[(0, 'Declined Liability'), (1, 'Accepted Liability')], default=0)),
                ('notify_channel', models.IntegerField(choices=[(0, 'Notify per email'), (1, 'Notify per SMS'), (2, 'Notify by calling')], default=2)),
                ('phone_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='profileatmatchrequest',
            constraint=models.UniqueConstraint(fields=('user', 'sdate'), name='unique_user_sdate_combination'),
        ),
    ]
