# Generated by Django 4.1.2 on 2022-11-28 13:14

import back.utils
import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.models.profile
import management.validators
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_read', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=255)),
                ('type', models.CharField(choices=[('none', 'No Type'), ('match', 'Match'), ('message', 'message')], default='none', max_length=255)),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.TextField(default='no-description')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_form_page', models.IntegerField(default=0)),
                ('user_form_state', models.CharField(choices=[('unfilled', 'Unfilled user form'), ('filled', 'Filled user form')], default='unfilled', max_length=255)),
                ('email_auth_hash', models.CharField(default=back.utils._double_uuid, max_length=255)),
                ('email_auth_pin', models.IntegerField(default=back.utils._rand_int5)),
                ('email_authenticated', models.BooleanField(default=False)),
                ('matching_state', models.CharField(choices=[('idle', 'Not Searching (Idle)'), ('searching', 'Searching')], default='idle', max_length=255)),
                ('unconfirmed_matches_stack', models.JSONField(default=list)),
                ('unread_chat_message_count', models.IntegerField(default=0)),
                ('unread_chat_message_count_update_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user_category', models.CharField(choices=[('undefined', 'Undefined'), ('spam', 'Spam'), ('legit', 'Legit'), ('test', 'Test')], default='undefined', max_length=255)),
                ('matches', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notifications', models.ManyToManyField(blank=True, related_name='n+', to='management.notification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_time_autenticated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('usr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to=settings.AUTH_USER_MODEL)),
                ('usr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAtMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_first_name])),
                ('second_name', models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_second_name])),
                ('birth_year', models.IntegerField(blank=True, default=1984)),
                ('user_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('learner', 'Language learner')], default='volunteer', max_length=255)),
                ('past_user_types', models.JSONField(blank=True, null=True)),
                ('target_group', models.CharField(choices=[('any.vol', 'Any group'), ('any.ler', 'Any group'), ('refugee.vol', 'Refugees only'), ('refugee.ler', 'Refugees only'), ('student.vol', 'Students only'), ('student.ler', 'Students only'), ('worker.vol', 'Workers only'), ('worker.ler', 'Workers only')], default='any.vol', max_length=255)),
                ('partner_sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=255)),
                ('speech_medium', models.CharField(choices=[('any.vol', 'Any'), ('any.ler', 'Any'), ('video.vol', 'Video only'), ('video.ler', 'Video only'), ('phone.vol', 'Phone only'), ('phone.ler', 'Phone only')], default='any.vol', max_length=255)),
                ('partner_location', models.CharField(choices=[('anywhere.vol', 'Anywhere'), ('anywhere.ler', 'Anywhere'), ('close.vol', 'Close'), ('close.ler', 'Close'), ('far.vol', 'Far'), ('far.ler', 'Far')], default='anywhere.vol', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('hostry', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=20)),
                ('additional_interests', models.TextField(blank=True, default='', max_length=300)),
                ('availability', models.JSONField(blank=True, default=management.validators.get_default_availability, null=True, validators=[management.validators.validate_availability])),
                ('liability', models.CharField(choices=[('declined', 'Declined Liability'), ('accepted', 'Accepted Liability')], default='declined', max_length=255)),
                ('notify_channel', models.CharField(choices=[('email', 'Notify per email'), ('sms', 'Notify per SMS'), ('call', 'Notify by calling')], default='email', max_length=255)),
                ('phone_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('language_skill_description', models.TextField(blank=True, default='', max_length=300)),
                ('lang_level', models.CharField(choices=[('level-0.vol', 'any'), ('level-0.ler', 'any'), ('level-1.vol', 'B1 = (everyday situations, stories, hopes)'), ('level-1.ler', 'B1 = (everyday situations, stories, hopes)'), ('level-2.vol', 'B2 = (fluent & spontaneous conversations, current events)'), ('level-2.ler', 'B2 = (fluent & spontaneous conversations, current events)'), ('level-3.vol', 'C1/C2 = (complex topics, hardly searching for words)'), ('level-3.ler', 'C1/C2 = (complex topics, hardly searching for words)')], default='level-0.vol', max_length=255)),
                ('image_type', models.CharField(choices=[('avatar', 'Avatar'), ('image', 'Image')], default='image', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=management.models.profile.PathRename('profile_pics/'))),
                ('avatar_config', models.TextField(blank=True, default='')),
                ('sdate', models.CharField(default=management.models.profile._date_string, max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_first_name])),
                ('second_name', models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_second_name])),
                ('birth_year', models.IntegerField(blank=True, default=1984)),
                ('user_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('learner', 'Language learner')], default='volunteer', max_length=255)),
                ('past_user_types', models.JSONField(blank=True, null=True)),
                ('target_group', models.CharField(choices=[('any.vol', 'Any group'), ('any.ler', 'Any group'), ('refugee.vol', 'Refugees only'), ('refugee.ler', 'Refugees only'), ('student.vol', 'Students only'), ('student.ler', 'Students only'), ('worker.vol', 'Workers only'), ('worker.ler', 'Workers only')], default='any.vol', max_length=255)),
                ('partner_sex', models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=255)),
                ('speech_medium', models.CharField(choices=[('any.vol', 'Any'), ('any.ler', 'Any'), ('video.vol', 'Video only'), ('video.ler', 'Video only'), ('phone.vol', 'Phone only'), ('phone.ler', 'Phone only')], default='any.vol', max_length=255)),
                ('partner_location', models.CharField(choices=[('anywhere.vol', 'Anywhere'), ('anywhere.ler', 'Anywhere'), ('close.vol', 'Close'), ('close.ler', 'Close'), ('far.vol', 'Far'), ('far.ler', 'Far')], default='anywhere.vol', max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('hostry', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=20)),
                ('additional_interests', models.TextField(blank=True, default='', max_length=300)),
                ('availability', models.JSONField(blank=True, default=management.validators.get_default_availability, null=True, validators=[management.validators.validate_availability])),
                ('liability', models.CharField(choices=[('declined', 'Declined Liability'), ('accepted', 'Accepted Liability')], default='declined', max_length=255)),
                ('notify_channel', models.CharField(choices=[('email', 'Notify per email'), ('sms', 'Notify per SMS'), ('call', 'Notify by calling')], default='email', max_length=255)),
                ('phone_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('language_skill_description', models.TextField(blank=True, default='', max_length=300)),
                ('lang_level', models.CharField(choices=[('level-0.vol', 'any'), ('level-0.ler', 'any'), ('level-1.vol', 'B1 = (everyday situations, stories, hopes)'), ('level-1.ler', 'B1 = (everyday situations, stories, hopes)'), ('level-2.vol', 'B2 = (fluent & spontaneous conversations, current events)'), ('level-2.ler', 'B2 = (fluent & spontaneous conversations, current events)'), ('level-3.vol', 'C1/C2 = (complex topics, hardly searching for words)'), ('level-3.ler', 'C1/C2 = (complex topics, hardly searching for words)')], default='level-0.vol', max_length=255)),
                ('image_type', models.CharField(choices=[('avatar', 'Avatar'), ('image', 'Image')], default='image', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to=management.models.profile.PathRename('profile_pics/'))),
                ('avatar_config', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchinScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('messages', models.JSONField()),
                ('matchable', models.BooleanField()),
                ('meta', models.JSONField()),
                ('from_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_usr', to=settings.AUTH_USER_MODEL)),
                ('to_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profileatmatchrequest',
            constraint=models.UniqueConstraint(fields=('user', 'sdate'), name='unique_user_sdate_combination'),
        ),
        migrations.AddConstraint(
            model_name='matchinscore',
            constraint=models.UniqueConstraint(fields=('from_usr', 'to_usr', 'relation_slug'), name='unique_from_to_usr_relation'),
        ),
    ]
