# Generated by Django 4.1.2 on 2022-11-17 16:13

from django.db import migrations, models
import management.models.profile
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_skill_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_avatar_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=management.models.profile.PathRename('profile_pics/')),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'avatar_profile_trans'), (1, 'image_profile_trans')], default=1),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='language_skill_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='profile_avatar_config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=management.models.profile.PathRename('profile_pics/')),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'avatar_profile_trans'), (1, 'image_profile_trans')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.JSONField(blank=True, null=True, validators=[management.validators.validate_availability]),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='availability',
            field=models.JSONField(blank=True, null=True, validators=[management.validators.validate_availability]),
        ),
    ]
