# Generated by Django 4.1.2 on 2022-11-14 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_read', models.DateTimeField(null=True)),
                ('state', models.IntegerField(choices=[(0, 'unread'), (1, 'read'), (2, 'archived')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'none'), (1, 'match'), (2, 'message')], default=0)),
                ('title', models.CharField(default='title', max_length=255)),
                ('description', models.TextField(default='no-description')),
                ('meta', models.JSONField(default={})),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
