# Generated by Django 4.1.2 on 2022-11-29 22:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='past_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('hostry', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('hostry', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
    ]
