# Generated by Django 4.1.2 on 2022-12-15 16:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretablesource',
            name='function_scoring_selection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('postal_code_distance_check', 'postal_code_distance_check'), ('volunteer_vs_leaner_check', 'volunteer_vs_leaner_check')], default=['postal_code_distance_check', 'volunteer_vs_leaner_check'], max_length=1000),
        ),
    ]
