# Generated by Django 4.1.2 on 2022-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('once', 'Once')], default='once', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
