# Generated by Django 4.1.2 on 2022-11-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='lang_level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Bild')], default=1),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Bild')], default=1),
        ),
    ]
