# Generated by Django 4.1.2 on 2022-11-23 02:01

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=None, max_length=150, validators=[
                                   management.validators.model_validate_first_name]),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='first_name',
            field=models.CharField(default=None, max_length=150, validators=[
                                   management.validators.model_validate_first_name]),
        ),
    ]
