# Generated by Django 4.1.2 on 2022-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language_skill_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='language_skill_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
