# Generated by Django 4.1.2 on 2022-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='past_user_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='past_user_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='user_form_page',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='user_form_state',
            field=models.IntegerField(default=0),
        ),
    ]
