# Generated by Django 4.1.2 on 2022-12-16 02:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_scoretablesource_function_scoring_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretablesource',
            name='function_scoring_selection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('postal_code_distance_check', 'postal_code_distance_check'), ('volunteer_vs_leaner_check', 'volunteer_vs_leaner_check'), ('time_slot_overlap_check', 'time_slot_overlap_check'), ('interests_overlap_check', 'interests_overlap_check')], default=['postal_code_distance_check', 'volunteer_vs_leaner_check', 'time_slot_overlap_check', 'interests_overlap_check'], max_length=1000),
        ),
    ]
