# Generated by Django 4.1.2 on 2022-11-23 02:23

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_second_name]),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='second_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.model_validate_second_name]),
        ),
    ]
