# Generated by Django 4.1.2 on 2022-12-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_communityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
