# Generated by Django 4.1.2 on 2022-11-21 16:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile_lang_level_profileatmatchrequest_lang_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport'), (1, 'Kunst'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang_level',
            field=models.IntegerField(choices=[(0, 'Level 0 (egal)'), (1, 'Level 1 (B1 = (Alltagssituationen, Geschichten, Hoffnungen))'), (2, 'Level 2 (B2 = (fließende & spontane Gespräche, aktuelles Geschehen))'), (3, 'Level 3 (C1 = (komplexe Themen, kaum nach Wörtern suchen))')], default=0),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport'), (1, 'Kunst'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='lang_level',
            field=models.IntegerField(choices=[(0, 'Level 0 (egal)'), (1, 'Level 1 (B1 = (Alltagssituationen, Geschichten, Hoffnungen))'), (2, 'Level 2 (B2 = (fließende & spontane Gespräche, aktuelles Geschehen))'), (3, 'Level 3 (C1 = (komplexe Themen, kaum nach Wörtern suchen))')], default=0),
        ),
    ]
