# Generated by Django 4.1.2 on 2022-11-14 21:30

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hash',
            field=models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
