# Generated by Django 4.1.2 on 2022-11-23 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_profile_second_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_time_autenticated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('usr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr1', to=settings.AUTH_USER_MODEL)),
                ('usr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
