# Generated by Django 4.1.2 on 2022-11-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_notification_hash_alter_notification_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
