# Generated by Django 4.1.2 on 2022-12-02 00:16

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_communityevent_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies')], max_length=255, unique=True)),
                ('name', models.CharField(default='master', max_length=255, unique=True)),
                ('hash', models.CharField(default=back.utils._double_uuid, max_length=255)),
                ('meta', models.JSONField(default={})),
            ],
        ),
    ]
