# Generated by Django 4.1.2 on 2022-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar_config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='profile_avatar_config',
            field=models.TextField(blank=True, default=''),
        ),
    ]
