# Generated by Django 4.1.2 on 2022-11-21 16:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_profile_interests_alter_profile_lang_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Image')], default=1),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='profile_image_type',
            field=models.IntegerField(choices=[(0, 'Avatar'), (1, 'Image')], default=1),
        ),
    ]
