# Generated by Django 4.1.2 on 2022-11-22 00:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_profile_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport'), (1, 'Art'), (2, 'Music'), (3, 'Literature'), (4, 'Movies'), (5, 'Fashion'), (6, 'Culture'), (7, 'Travel'), (8, 'Food'), (9, 'Politics'), (10, 'Nature'), (11, 'Science'), (12, 'Technology'), (13, 'History'), (14, 'Religion'), (15, 'Sociology'), (16, 'Family'), (17, 'Psycology'), (18, 'Personal development')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport'), (1, 'Art'), (2, 'Music'), (3, 'Literature'), (4, 'Movies'), (5, 'Fashion'), (6, 'Culture'), (7, 'Travel'), (8, 'Food'), (9, 'Politics'), (10, 'Nature'), (11, 'Science'), (12, 'Technology'), (13, 'History'), (14, 'Religion'), (15, 'Sociology'), (16, 'Family'), (17, 'Psycology'), (18, 'Personal development')], max_length=20),
        ),
    ]
