# Generated by Django 4.1.2 on 2022-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_backendstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendstate',
            name='slug',
            field=models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies'), ('db-filled-base-management-user-profile', 'Base Management User Profile')], max_length=255, unique=True),
        ),
    ]
