# Generated by Django 4.1.2 on 2022-11-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_notification_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='notifications',
            field=models.ManyToManyField(related_name='n+', to='management.notification'),
        ),
    ]
