# Generated by Django 4.1.2 on 2022-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_profile_profile_avatar_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='additional_interests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
