# Generated by Django 4.1.2 on 2022-11-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='unread_message_count',
            new_name='unread_chat_message_count',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='unread_message_count_update_time',
            new_name='unread_chat_message_count_update_time',
        ),
        migrations.AddField(
            model_name='state',
            name='matching_state',
            field=models.IntegerField(choices=[(0, 'Not Searching (Idle)'), (1, 'Searching')], default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='unconfirmed_matches_stack',
            field=models.JSONField(default=list),
        ),
    ]
