# Generated by Django 4.1.2 on 2022-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speech_medium',
            field=models.IntegerField(choices=[(0, 'Any medium'), (1, 'Video only'), (2, 'Phone only')], default=0),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='speech_medium',
            field=models.IntegerField(choices=[(0, 'Any medium'), (1, 'Video only'), (2, 'Phone only')], default=0),
        ),
    ]
