# Generated by Django 4.1.2 on 2022-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_profile_additional_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(blank=True, default=1984),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='birth_year',
            field=models.IntegerField(blank=True, default=1984),
        ),
    ]
