# Generated by Django 4.1.2 on 2022-12-18 14:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_profile_gender_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_backend_user_h256_pk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psycology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
    ]
