# Generated by Django 4.1.2 on 2022-11-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_state_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='user_form_state',
            field=models.IntegerField(choices=[(0, 'Unfilled user form'), (1, 'Filled user form')], default=0),
        ),
    ]
