# Generated by Django 4.1.2 on 2022-12-02 12:02

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_backendstate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendstate',
            name='name',
            field=models.CharField(default=back.utils._double_uuid, max_length=255, unique=True),
        ),
    ]
