# Generated by Django 4.1.2 on 2022-12-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_backendstate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendstate',
            name='name',
            field=models.CharField(default='master', max_length=255, unique=True),
        ),
    ]
