# Generated by Django 4.1.2 on 2022-11-16 12:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_state_user_form_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='liability',
            field=models.IntegerField(choices=[(0, 'Declined Liability'), (1, 'Accepted Liability')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_channel',
            field=models.IntegerField(choices=[(0, 'Notify per email'), (1, 'Notify per SMS'), (2, 'Notify by calling')], default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_location',
            field=models.IntegerField(choices=[(0, 'Location Anywhere'), (1, 'Location close'), (2, 'Location far')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_sex',
            field=models.IntegerField(choices=[(0, 'Any sex'), (1, 'Male only'), (2, 'Female only')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Sport (interest)'), (1, 'Art (interest)'), (2, 'Music (interest)'), (3, 'Literature (interest)'), (4, 'Movies (interest)'), (5, 'Fashion (interest)'), (6, 'Culture (interest)'), (7, 'Travel (interest)'), (8, 'Food (interest)'), (9, 'Politics (interest)'), (10, 'Nature (interest)'), (11, 'Science (interest)'), (12, 'Technology (interest)'), (13, 'History (interest)'), (14, 'Religion (interest)'), (15, 'Sociology (interest)'), (16, 'Family (interest)'), (17, 'Psycology (interest)'), (18, 'Personal development (interest)')], max_length=20),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='liability',
            field=models.IntegerField(choices=[(0, 'Declined Liability'), (1, 'Accepted Liability')], default=0),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='notify_channel',
            field=models.IntegerField(choices=[(0, 'Notify per email'), (1, 'Notify per SMS'), (2, 'Notify by calling')], default=2),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='partner_location',
            field=models.IntegerField(choices=[(0, 'Location Anywhere'), (1, 'Location close'), (2, 'Location far')], default=0),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='partner_sex',
            field=models.IntegerField(choices=[(0, 'Any sex'), (1, 'Male only'), (2, 'Female only')], default=0),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
