# Generated by Django 4.1.2 on 2022-12-24 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_user_old_backend_user_h256_pk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='unread_chat_message_count',
        ),
        migrations.RemoveField(
            model_name='state',
            name='unread_chat_message_count_update_time',
        ),
        migrations.AddField(
            model_name='state',
            name='unread_messages_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='state',
            name='unread_state_update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
