# Generated by Django 4.1.2 on 2022-11-16 12:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_profile_interests_profile_liability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='phone_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
