# Generated by Django 4.1.2 on 2022-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_state_unread_chat_message_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='unread_messages_state',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
