# Generated by Django 4.1.2 on 2022-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_backendstate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='unconfirmed_matches_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
