# Generated by Django 4.1.2 on 2022-11-16 14:01

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_profile_phone_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='first_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='second_name',
            field=models.CharField(default=None, max_length=150, validators=[management.validators.validate_name]),
        ),
    ]
