# Generated by Django 4.1.2 on 2022-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_state_unconfirmed_matches_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_config',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='avatar_config',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
