# Generated by Django 4.1.2 on 2023-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_state_unread_messages_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretablesource',
            name='speech_medium_scores',
            field=models.TextField(default=''),
        ),
    ]
