# Generated by Django 4.1.2 on 2022-11-16 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_profile_first_name_alter_profile_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='n+', to='management.notification'),
        ),
    ]
