# Generated by Django 4.1.2 on 2023-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_scoretablesource_speech_medium_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('link', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
