# Generated by Django 4.1.2 on 2022-12-05 14:20

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_profile_avatar_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hash',
            field=models.CharField(default=back.utils._double_uuid, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default=back.utils._double_uuid, max_length=255),
        ),
    ]
