# Generated by Django 4.1.2 on 2022-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_state_matches_alter_state_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='user_category',
            field=models.IntegerField(choices=[(0, 'Undefined (user-c)'), (1, 'Spam (user-c)'), (2, 'Legit (user-c)'), (3, 'Test (user-c)')], default=0),
        ),
    ]
