# Generated by Django 4.1.2 on 2022-12-08 20:45

import back.utils
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_room_hash_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='auto_login_api_token',
            field=models.CharField(default=back.utils._double_uuid, max_length=255),
        ),
        migrations.AddField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)')], max_length=1000, null=True),
        ),
    ]
