# Generated by Django 4.1.2 on 2023-01-06 21:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('state.tags-spam', 'state.tags-spam'), ('state.tags-wrong-language-level', 'state.tags-wrong-language-level'), ('state.tags-name-not-correct', 'state.tags-name-not-correct'), ('state.tags-description-lang-wrong', 'state.tags-description-lang-wrong'), ('state.tags-language-level-to-low-or-uncertain', 'state.tags-language-level-to-low-or-uncertain'), ('state.tags-too-young', 'state.tags-too-young'), ('state.tags-doesnt-awnser-match', 'state.tags-doesnt-awnser-match'), ('state.tags-postal-code-invalid', 'state.tags-postal-code-invalid'), ('state.tags-wants-to-learn-other-language', 'state.tags-wants-to-learn-other-language'), ('state.tags-requested-to-be-deleted', 'state.tags-requested-to-be-deleted'), ('state.tags-uncertain-if-vol-or-learner', 'state.tags-uncertain-if-vol-or-learner')], max_length=1000, null=True),
        ),
    ]
