# Generated by Django 4.1.2 on 2022-12-09 12:20

import back.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_state_auto_login_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTableSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='latest', max_length=255)),
                ('hash', models.CharField(default=back.utils._double_uuid, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_group', models.TextField()),
                ('target_group_messages', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='backendstate',
            name='slug',
            field=models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies'), ('db-filled-base-management-user-profile', 'Base Management User Profile'), ('db-created-default-score-source', 'Default Score Source Created')], max_length=255, unique=True),
        ),
    ]
