# Generated by Django 4.1.2 on 2022-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_scoretablesource_alter_backendstate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendstate',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='avatar_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
