# Generated by Django 4.1.2 on 2022-12-09 20:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_backendstate_meta_alter_profile_avatar_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretablesource',
            name='target_group',
        ),
        migrations.AddField(
            model_name='scoretablesource',
            name='function_scoring_selection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('postal_code_distance_check', 'postal_code_distance_check')], default=['postal_code_distance_check'], max_length=1000),
        ),
        migrations.AddField(
            model_name='scoretablesource',
            name='language_level_scores',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretablesource',
            name='partner_location_scores',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretablesource',
            name='target_group_scores',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
