# Generated by Django 4.1.2 on 2022-12-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_scoretablesource_target_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretablesource',
            name='language_level_scores',
        ),
    ]
