# Generated by Django 4.1.2 on 2023-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'Notify per email'), ('sms', 'Notify per SMS')], default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'Notify per email'), ('sms', 'Notify per SMS')], default='email', max_length=255),
        ),
    ]
