# Generated by Django 4.1.2 on 2022-12-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_scoretablesource_language_level_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretablesource',
            name='language_level_scores',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scoretablesource',
            name='partner_location_scores',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scoretablesource',
            name='target_group_messages',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='scoretablesource',
            name='target_group_scores',
            field=models.TextField(default=''),
        ),
    ]
