# Generated by Django 4.1.2 on 2023-01-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_profile_notify_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Language learner'), ('volunteer', 'Volunteer')], default='learner', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='user_type',
            field=models.CharField(choices=[('learner', 'Language learner'), ('volunteer', 'Volunteer')], default='learner', max_length=255),
        ),
    ]
