# Generated by Django 4.1.2 on 2023-01-16 11:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretablesource',
            name='function_scoring_selection',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('postal_code_distance_check', 'postal_code_distance_check'), ('volunteer_vs_leaner_check', 'volunteer_vs_leaner_check'), ('time_slot_overlap_check', 'time_slot_overlap_check'), ('interests_overlap_check', 'interests_overlap_check'), ('partner_sex_prediction', 'partner_sex_prediction'), ('searching_since_check', 'searching_since_check')], default=['postal_code_distance_check', 'volunteer_vs_leaner_check', 'time_slot_overlap_check', 'interests_overlap_check', 'partner_sex_prediction', 'searching_since_check'], max_length=1000),
        ),
    ]
