# Generated by Django 4.1.2 on 2023-01-17 17:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_scoretablesource_function_scoring_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-stats', 'Is allowed to view the stats')], max_length=1000, null=True),
        ),
    ]
