# Generated by Django 4.1.2 on 2022-12-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_matchinscore_rendered_results_md_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinscore',
            name='current_score',
            field=models.BooleanField(default=True),
        ),
    ]
