# Generated by Django 4.1.2 on 2022-12-11 13:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_matchinscore_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('state.tags-spam', 'Spam'), ('state.tags-wrong-language-level', 'Wrong Lang Level')], max_length=1000, null=True),
        ),
    ]
