# Generated by Django 4.1.2 on 2023-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='description',
            field=models.TextField(blank=True, default='', max_length=999),
        ),
    ]
