# Generated by Django 4.1.2 on 2022-12-11 15:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_state_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('state.tags-spam', 'Spam'), ('state.tags-wrong-language-level', 'Wrong Lang Level'), ('state.tags-name-not-correct', 'Name Not Correct'), ('state.tags-description-lang-wrong', 'Description Lang Wrong'), ('state.tags-language-level-to-low-or-uncertain', 'Language Level To Low Or Uncertain'), ('state.tags-too-young', 'Too Yung'), ('state.tags-doesnt-awnser-match', 'Doesnt Awnser Match'), ('state.tags-postal-code-invalid', 'Postal Code Invalid'), ('state.tags-wants-to-learn-other-language', 'Wants To Learn Other Language'), ('state.tags-requested-to-be-deleted', 'Requested To Be Deleted'), ('state.tags-uncertain-if-vol-or-learner', 'Uncertain If Vol Or Learner')], max_length=1000, null=True),
        ),
    ]
