# Generated by Django 4.1.2 on 2023-01-24 13:59

import back.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('attachment1', models.BinaryField(blank=True, null=True)),
                ('attachment2', models.BinaryField(blank=True, null=True)),
                ('attachment3', models.BinaryField(blank=True, null=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
