# Generated by Django 4.1.2 on 2023-02-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_helpmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL)),
                ('who_unmatched', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unmatcher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
