# Generated by Django 4.1.2 on 2022-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_state_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
