# Generated by Django 4.1.2 on 2023-02-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_pastmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('source_lang', models.CharField(max_length=255)),
                ('dest_lang', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('translation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
