# Generated by Django 4.1.2 on 2023-04-16 11:32

from django.db import migrations, models
import management.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_translationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang_skill',
            field=models.JSONField(default=management.models.profile.base_lang_skill),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='lang_skill',
            field=models.JSONField(default=management.models.profile.base_lang_skill),
        ),
    ]
