# Generated by Django 4.1.2 on 2023-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_profile_lang_skill_profileatmatchrequest_lang_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', 'Dont want to say'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='partner_gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='gender',
            field=models.CharField(choices=[('any', 'Dont want to say'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='partner_gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male only'), ('female', 'Female only')], default='any', max_length=255),
        ),
    ]
