# Generated by Django 4.1.2 on 2023-05-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models.unconfirmed_matches
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_profile_gender_profile_partner_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnconfirmedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('closed', models.BooleanField(default=False)),
                ('potential_matching_created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=management.models.unconfirmed_matches.seven_days_from_now)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmed_match_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmed_match_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
