# Generated by Django 4.1.2 on 2023-05-23 00:40

from django.db import migrations, models
import django.db.models.deletion
import management.models.settings
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_nologinform_unconfirmedmatch_stillincontactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('unsubscibed_options', multiselectfield.db.fields.MultiSelectField(choices=[('interview_requests', 'Interview Requests')], default=[], max_length=500)),
                ('unsubscribed_categories', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='email_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.emailsettings', unique=False, null=True),
        ),
    ]
