# Generated by Django 4.1.2 on 2023-05-14 15:01

import back.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_unconfirmedmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoLoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, default=back.utils._double_uuid, max_length=100, unique=True)),
                ('form_type', models.CharField(choices=[('still_in_contact', 'Still In Contact')], default='still_in_contact', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StillInContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('still_in_contact', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='still_in_contact_form', to='management.nologinform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='still_in_contact_form_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
