# Generated by Django 4.1.2 on 2023-05-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_nologinform_stillincontactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stillincontactform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='stillincontactform',
            name='user',
        ),
        migrations.DeleteModel(
            name='NoLoginForm',
        ),
        migrations.DeleteModel(
            name='StillInContactForm',
        ),
    ]
