# Generated by Django 4.1.2 on 2023-05-23 14:18

from django.db import migrations
import uuid

def gen_email_settings(apps, schema_editor):
    settings_models = apps.get_model('management', 'Settings')
    email_settings_models = apps.get_model('management', 'EmailSettings')
    for row in settings_models.objects.all():
        row.email_settings = email_settings_models.objects.create()
        row.save(update_fields=['email_settings'])

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_emailsettings_settings_email_settings'),
    ]

    operations = [
        migrations.RunPython(gen_email_settings, reverse_code=migrations.RunPython.noop),
    ]
