# Generated by Django 4.1.2 on 2023-07-18 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models.settings
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20230523_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_verification_reminder1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='user_form_unfinished_reminder1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='user_form_unfinished_reminder2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unconfirmedmatch',
            name='expired_mail_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unconfirmedmatch',
            name='send_inital_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='unsubscibed_options',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('interview_requests', 'Interview Requests'), ('survery_requests', 'Survery Requests'), ('finish_reminders', 'Finish Reminders')], default=[], max_length=500),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_settings',
            field=models.OneToOneField(default=management.models.settings.create_email_settings, on_delete=django.db.models.deletion.CASCADE, to='management.emailsettings'),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats')], max_length=1000, null=True),
        ),
    ]
