# Generated by Django 4.1.2 on 2023-05-31 14:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='unsubscibed_options',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('interview_requests', 'Interview Requests'), ('survery_requests', 'Survery Requests')], default=[], max_length=500),
        ),
    ]
