# Generated by Django 4.1.2 on 2023-07-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmedmatch',
            name='learner_when_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unconfirmed_match_learner_when_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
