# Generated by Django 4.1.2 on 2023-07-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_unconfirmedmatch_learner_when_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='report_unmatch',
            field=models.JSONField(default=list),
        ),
    ]
