# Generated by Django 4.1.2 on 2023-08-24 13:53

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_match_report_unmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='managed_users',
            field=models.ManyToManyField(blank=True, related_name='managed_users_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users')], max_length=1000, null=True),
        ),
    ]
