# Generated by Django 4.1.2 on 2023-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_state_managed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
