# Generated by Django 4.1.2 on 2023-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_state_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='still_active_reminder_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='still_active_reminder_send',
            field=models.BooleanField(default=False),
        ),
    ]
