# Generated by Django 4.1.2 on 2023-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_emailsettings_email_verification_reminder1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmedmatch',
            name='expired_mail_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unconfirmedmatch',
            name='send_inital_mail',
            field=models.BooleanField(default=False),
        ),
    ]
