# Generated by Django 4.1.2 on 2023-09-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_mangementtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='management_tasks',
            field=models.ManyToManyField(blank=True, related_name='management_tasks', to='management.mangementtask'),
        ),
    ]
