# Generated by Django 4.1.2 on 2023-09-11 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_mangementtask_state_management_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twilio_response', models.JSONField(default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_recipient', to=settings.AUTH_USER_MODEL)),
                ('send_initator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_send_initator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
