# Generated by Django 4.1.2 on 2023-09-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_smsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='still_in_contact_mail_send',
            field=models.BooleanField(default=False),
        ),
    ]
