# Generated by Django 4.1.2 on 2023-10-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_match_still_in_contact_mail_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liability_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='liability_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
