# Generated by Django 4.1.2 on 2023-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_profile_liability_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='require_pre_matching_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='backendstate',
            name='slug',
            field=models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies'), ('db-filled-base-management-user-profile', 'Base Management User Profile'), ('db-created-default-score-source', 'Default Score Source Created'), ('pre-matching-call-active', 'Pre Matching Call Active')], max_length=255, unique=True),
        ),
    ]
