# Generated by Django 4.1.2 on 2023-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_state_require_pre_matching_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='display_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=255),
        ),
    ]
