# Generated by Django 4.1.2 on 2023-10-11 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_profile_display_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='prematch_booking_code',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
