# Generated by Django 4.1.2 on 2023-10-16 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_state_prematch_booking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('category_name', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='user_decks', to='management.cardcontent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='user_deck',
            field=models.ManyToManyField(related_name='state_user_decks', to='management.cardcontent'),
        ),
    ]
