# Generated by Django 4.1.2 on 2023-10-18 09:27

from django.db import migrations, models
import management.models.question_deck
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_cardcontent_userdeck_state_user_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeck',
            old_name='categories',
            new_name='content_id',
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='content',
            field=models.JSONField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='slug',
            field=models.SlugField(unique=True, validators=[management.models.question_deck.validate_unique]),
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, validators=[management.models.question_deck.validate_unique_content]),
        ),
    ]
