# Generated by Django 4.1.2 on 2023-10-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_cardcontent_userdeck_state_user_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='unresponsive',
            field=models.BooleanField(default=False),
        ),
    ]
