# Generated by Django 4.1.2 on 2023-11-26 18:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_state_unresponsive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='unsubscibed_options',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('interview_requests', 'Interview Requests'), ('survery_requests', 'Survery Requests'), ('finish_reminders', 'Finish Reminders'), ('event_announcement', 'Event Announcement')], default=[], max_length=500),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users'), ('uncensored-admin-matcher', 'Is allowed to match users without censorship')], max_length=1000, null=True),
        ),
    ]
