# Generated by Django 4.1.2 on 2023-10-26 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_state_unresponsive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('time_left', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_connection_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users'), ('uncensored-admin-matcher', 'Is allowed to match users without censorship')], max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ConsumerConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('connections', models.ManyToManyField(related_name='consumer_connections_connections', to='management.connections')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_connections_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
