# Generated by Django 4.1.2 on 2023-12-11 14:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_connections_consumerconnections'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_target_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='other_target_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', "Don't want to say"), ('male', 'Male'), ('female', 'Female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psychology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'to be notified by e-mail only.'), ('sms', 'to be notified by e-mail & SMS.')], default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_group',
            field=models.CharField(choices=[('any.vol', 'other'), ('any.ler', 'other'), ('refugee.vol', 'Refugees'), ('refugee.ler', 'Refugees'), ('student.vol', 'Students'), ('student.ler', 'Students'), ('worker.vol', 'Workers'), ('worker.ler', 'Workers')], default='any.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='gender',
            field=models.CharField(choices=[('any', "Don't want to say"), ('male', 'Male'), ('female', 'Female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'Sport'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('video', 'Video'), ('fashion', 'Fashion'), ('culture', 'Culture'), ('travel', 'Travel'), ('food', 'Food'), ('politics', 'Politics'), ('nature', 'Nature'), ('science', 'Science'), ('technology', 'Technology'), ('history', 'History'), ('religion', 'Religion'), ('sociology', 'Sociology'), ('family', 'Family'), ('psycology', 'Psychology'), ('personal-development', 'Personal development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'to be notified by e-mail only.'), ('sms', 'to be notified by e-mail & SMS.')], default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_group',
            field=models.CharField(choices=[('any.vol', 'other'), ('any.ler', 'other'), ('refugee.vol', 'Refugees'), ('refugee.ler', 'Refugees'), ('student.vol', 'Students'), ('student.ler', 'Students'), ('worker.vol', 'Workers'), ('worker.ler', 'Workers')], default='any.vol', max_length=255),
        ),
    ]
