# Generated by Django 4.1.2 on 2023-12-11 15:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_profile_other_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any.vol', 'other'), ('any.ler', 'other'), ('refugee.vol', 'Refugees'), ('refugee.ler', 'Refugees'), ('student.vol', 'Students'), ('student.ler', 'Students'), ('worker.vol', 'Workers'), ('worker.ler', 'Workers')], max_length=1000),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any.vol', 'other'), ('any.ler', 'other'), ('refugee.vol', 'Refugees'), ('refugee.ler', 'Refugees'), ('student.vol', 'Students'), ('student.ler', 'Students'), ('worker.vol', 'Workers'), ('worker.ler', 'Workers')], max_length=1000),
        ),
    ]
