# Generated by Django 4.1.2 on 2023-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_profile_target_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
