# Generated by Django 4.1.2 on 2023-12-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_profile_newsletter_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='display_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', max_length=255),
        ),
    ]
