# Generated by Django 4.1.2 on 2024-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_alter_profile_display_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='min_lang_level_partner',
            field=models.CharField(choices=[('level-0', 'A1 & A2 (beginner level)'), ('level-1', 'B1 (everyday situations, stories)'), ('level-2', 'B2 (fluent & spontaneous conversations)'), ('level-3', 'C1/C2 (complex topics)')], default='level-0', max_length=255),
        ),
        migrations.AddField(
            model_name='profileatmatchrequest',
            name='min_lang_level_partner',
            field=models.CharField(choices=[('level-0', 'A1 & A2 (beginner level)'), ('level-1', 'B1 (everyday situations, stories)'), ('level-2', 'B2 (fluent & spontaneous conversations)'), ('level-3', 'C1/C2 (complex topics)')], default='level-0', max_length=255),
        ),
    ]
