# Generated by Django 4.1.2 on 2024-01-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_profile_min_lang_level_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoUserMatchingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('scoring_results', models.JSONField(default=dict)),
                ('latest_update', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_user_matching_score_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_user_matching_score_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
