# Generated by Django 4.1.2 on 2024-01-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_twousermatchingscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerconnections',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='consumerconnections',
            name='user',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.DeleteModel(
            name='ConsumerConnections',
        ),
    ]
