# Generated by Django 4.1.2 on 2024-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_remove_consumerconnections_connections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='MatchinScore',
            name='from_usr',
        ),
        migrations.RemoveField(
            model_name='MatchinScore',
            name='to_usr',
        ),
        migrations.DeleteModel(
            name='ScoreTableSource',
        ),
        migrations.AddField(
            model_name='twousermatchingscore',
            name='matchable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MatchinScore',
        ),
    ]
