# Generated by Django 4.1.2 on 2024-02-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.models.question_deck
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_remove_matchinscore_from_usr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_id', models.IntegerField(default=0, editable=False, unique=True)),
                ('content', models.JSONField(default=management.models.question_deck._base_translations_dict)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCardCategories',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_id', models.IntegerField(default=0, editable=False, unique=True)),
                ('content', models.JSONField(default=management.models.question_deck._base_translations_dict)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCardsDeck',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cards', models.ManyToManyField(blank=True, related_name='cards', to='management.questioncard')),
                ('cards_archived', models.ManyToManyField(blank=True, related_name='cards_archived', to='management.questioncard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='state',
            name='user_deck',
        ),
        migrations.DeleteModel(
            name='CardContent',
        ),
        migrations.DeleteModel(
            name='UserDeck',
        ),
        migrations.AddField(
            model_name='questioncard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.questioncardcategories'),
        ),
        migrations.AddField(
            model_name='state',
            name='question_card_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.questioncardsdeck'),
        ),
    ]
