# Generated by Django 4.1.2 on 2024-02-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_questioncard_questioncardcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='had_prematching_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='question_card_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.questioncardsdeck'),
        ),
    ]
