# Generated by Django 4.1.2 on 2024-02-11 13:35

from django.db import migrations, models
import management.models.question_deck


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_state_had_prematching_call_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncardsdeck',
            name='cards',
            field=models.ManyToManyField(default=management.models.question_deck._default_cards, related_name='cards', to='management.questioncard'),
        ),
    ]
