# Generated by Django 4.1.2 on 2024-02-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_alter_questioncardsdeck_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncardsdeck',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='management.questioncard'),
        ),
        migrations.CreateModel(
            name='PreMatchingAppointment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
