# Generated by Django 4.1.2 on 2024-02-11 19:52

from django.db import migrations, models
import django.db.models.deletion
import management.models.state


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_alter_questioncardsdeck_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='question_card_deck',
            field=models.ForeignKey(blank=True, default=management.models.state._inital_question_card_deck, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.questioncardsdeck'),
        ),
    ]
