# Generated by Django 4.1.2 on 2024-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_alter_questioncardsdeck_cards_prematchingappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('two_step_verification', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
