# Generated by Django 5.0.2 on 2024-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_newslettersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
