# Generated by Django 5.0.2 on 2024-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_state_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', "Don't want to say"), ('male', 'Male'), ('female', 'Female')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='gender',
            field=models.CharField(choices=[('any', "Don't want to say"), ('male', 'Male'), ('female', 'Female')], default=None, max_length=255, null=True),
        ),
    ]
