# Generated by Django 5.0.2 on 2024-05-23 14:30

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_state_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'model.community_event.frequency.weekly'), ('once', 'model.community_event.frequency.once')], default='once', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(default='notification.no_description'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('unread', 'notification.state.unread'), ('read', 'notification.state.read'), ('archived', 'notification.state.archived')], default='unread', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='notification.title', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('none', 'notification.type.none'), ('match', 'notification.type.match'), ('message', 'notification.type.message')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_language',
            field=models.CharField(choices=[('de', 'profile.display_language.de'), ('en', 'profile.display_language.en')], default='de', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', 'profile.gender.any'), ('male', 'profile.gender.male'), ('female', 'profile.gender.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_type',
            field=models.CharField(choices=[('avatar', 'profile.image_type.avatar'), ('image', 'profile.image_type.image')], default='image', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'profile.interest.sport'), ('art', 'profile.interest.art'), ('music', 'profile.interest.music'), ('literature', 'profile.interest.literature'), ('video', 'profile.interest.video'), ('fashion', 'profile.interest.fashion'), ('culture', 'profile.interest.culture'), ('travel', 'profile.interest.travel'), ('food', 'profile.interest.food'), ('politics', 'profile.interest.politics'), ('nature', 'profile.interest.nature'), ('science', 'profile.interest.science'), ('technology', 'profile.interest.technology'), ('history', 'profile.interest.history'), ('religion', 'profile.interest.religion'), ('sociology', 'profile.interest.sociology'), ('family', 'profile.interest.family'), ('psycology', 'profile.interest.pychology'), ('personal-development', 'profile.interest.personal_development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang_level',
            field=models.CharField(choices=[('level-0.vol', 'profile.lang_level.level_0_vol'), ('level-0.ler', 'profile.lang_level.level_0_ler'), ('level-1.vol', 'profile.lang_level.level_1_vol'), ('level-1.ler', 'profile.lang_level.level_1_ler'), ('level-2.vol', 'profile.lang_level.level_2_vol'), ('level-2.ler', 'profile.lang_level.level_2_ler'), ('level-3.vol', 'profile.lang_level.level_3_vol'), ('level-3.ler', 'profile.lang_level.level_3_ler')], default='level-0.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liability',
            field=models.CharField(choices=[('declined', 'profile.liability.declined'), ('accepted', 'profile.liability.accepted')], default='declined', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_lang_level_partner',
            field=models.CharField(choices=[('level-0', 'profile.min_lang_level_partner.level_0'), ('level-1', 'profile.min_lang_level_partner.level_1'), ('level-2', 'profile.min_lang_level_partner.level_2'), ('level-3', 'profile.min_lang_level_partner.level_3')], default='level-0', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'profile.notification_channel.email'), ('sms', 'profile.notification_channel.sms')], default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_gender',
            field=models.CharField(choices=[('any', 'profile.partner_gender.any'), ('male', 'profile.partner_gender.male'), ('female', 'profile.partner_gender.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_location',
            field=models.CharField(choices=[('anywhere.vol', 'profile.partner_location.anywhere_vol'), ('anywhere.ler', 'profile.partner_location.anywhere_ler'), ('close.vol', 'profile.partner_location.close_vol'), ('close.ler', 'profile.partner_location.close_ler'), ('far.vol', 'profile.partner_location.far_vol'), ('far.ler', 'profile.partner_location.far_ler')], default='anywhere.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_sex',
            field=models.CharField(choices=[('any', 'profile.partner_sex.any'), ('male', 'profile.partner_sex.male'), ('female', 'profile.partner_sex.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speech_medium',
            field=models.CharField(choices=[('any.vol', 'profile.speech_medium.any_vol'), ('any.ler', 'profile.speech_medium.any_ler'), ('video.vol', 'profile.speech_medium.video_vol'), ('video.ler', 'profile.speech_medium.video_ler'), ('phone.vol', 'profile.speech_medium.phone_vol'), ('phone.ler', 'profile.speech_medium.phone_ler')], default='any.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_group',
            field=models.CharField(choices=[('any.vol', 'profile.target_group.any_vol'), ('any.ler', 'profile.target_group.any_ler'), ('refugee.vol', 'profile.target_group.refugee_vol'), ('refugee.ler', 'profile.target_group.refugee_ler'), ('student.vol', 'profile.target_group.student_vol'), ('student.ler', 'profile.target_group.student_ler'), ('worker.vol', 'profile.target_group.worker_vol'), ('worker.ler', 'profile.target_group.worker_ler')], default='any.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any.vol', 'profile.target_group.any_vol'), ('any.ler', 'profile.target_group.any_ler'), ('refugee.vol', 'profile.target_group.refugee_vol'), ('refugee.ler', 'profile.target_group.refugee_ler'), ('student.vol', 'profile.target_group.student_vol'), ('student.ler', 'profile.target_group.student_ler'), ('worker.vol', 'profile.target_group.worker_vol'), ('worker.ler', 'profile.target_group.worker_ler')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('learner', 'profile.user_type.learner'), ('volunteer', 'profile.user_type.volunteer')], default='learner', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='display_language',
            field=models.CharField(choices=[('de', 'profile.display_language.de'), ('en', 'profile.display_language.en')], default='de', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='gender',
            field=models.CharField(choices=[('any', 'profile.gender.any'), ('male', 'profile.gender.male'), ('female', 'profile.gender.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='image_type',
            field=models.CharField(choices=[('avatar', 'profile.image_type.avatar'), ('image', 'profile.image_type.image')], default='image', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sport', 'profile.interest.sport'), ('art', 'profile.interest.art'), ('music', 'profile.interest.music'), ('literature', 'profile.interest.literature'), ('video', 'profile.interest.video'), ('fashion', 'profile.interest.fashion'), ('culture', 'profile.interest.culture'), ('travel', 'profile.interest.travel'), ('food', 'profile.interest.food'), ('politics', 'profile.interest.politics'), ('nature', 'profile.interest.nature'), ('science', 'profile.interest.science'), ('technology', 'profile.interest.technology'), ('history', 'profile.interest.history'), ('religion', 'profile.interest.religion'), ('sociology', 'profile.interest.sociology'), ('family', 'profile.interest.family'), ('psycology', 'profile.interest.pychology'), ('personal-development', 'profile.interest.personal_development')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='lang_level',
            field=models.CharField(choices=[('level-0.vol', 'profile.lang_level.level_0_vol'), ('level-0.ler', 'profile.lang_level.level_0_ler'), ('level-1.vol', 'profile.lang_level.level_1_vol'), ('level-1.ler', 'profile.lang_level.level_1_ler'), ('level-2.vol', 'profile.lang_level.level_2_vol'), ('level-2.ler', 'profile.lang_level.level_2_ler'), ('level-3.vol', 'profile.lang_level.level_3_vol'), ('level-3.ler', 'profile.lang_level.level_3_ler')], default='level-0.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='liability',
            field=models.CharField(choices=[('declined', 'profile.liability.declined'), ('accepted', 'profile.liability.accepted')], default='declined', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='min_lang_level_partner',
            field=models.CharField(choices=[('level-0', 'profile.min_lang_level_partner.level_0'), ('level-1', 'profile.min_lang_level_partner.level_1'), ('level-2', 'profile.min_lang_level_partner.level_2'), ('level-3', 'profile.min_lang_level_partner.level_3')], default='level-0', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='notify_channel',
            field=models.CharField(choices=[('email', 'profile.notification_channel.email'), ('sms', 'profile.notification_channel.sms')], default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='partner_gender',
            field=models.CharField(choices=[('any', 'profile.partner_gender.any'), ('male', 'profile.partner_gender.male'), ('female', 'profile.partner_gender.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='partner_location',
            field=models.CharField(choices=[('anywhere.vol', 'profile.partner_location.anywhere_vol'), ('anywhere.ler', 'profile.partner_location.anywhere_ler'), ('close.vol', 'profile.partner_location.close_vol'), ('close.ler', 'profile.partner_location.close_ler'), ('far.vol', 'profile.partner_location.far_vol'), ('far.ler', 'profile.partner_location.far_ler')], default='anywhere.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='partner_sex',
            field=models.CharField(choices=[('any', 'profile.partner_sex.any'), ('male', 'profile.partner_sex.male'), ('female', 'profile.partner_sex.female')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='speech_medium',
            field=models.CharField(choices=[('any.vol', 'profile.speech_medium.any_vol'), ('any.ler', 'profile.speech_medium.any_ler'), ('video.vol', 'profile.speech_medium.video_vol'), ('video.ler', 'profile.speech_medium.video_ler'), ('phone.vol', 'profile.speech_medium.phone_vol'), ('phone.ler', 'profile.speech_medium.phone_ler')], default='any.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_group',
            field=models.CharField(choices=[('any.vol', 'profile.target_group.any_vol'), ('any.ler', 'profile.target_group.any_ler'), ('refugee.vol', 'profile.target_group.refugee_vol'), ('refugee.ler', 'profile.target_group.refugee_ler'), ('student.vol', 'profile.target_group.student_vol'), ('student.ler', 'profile.target_group.student_ler'), ('worker.vol', 'profile.target_group.worker_vol'), ('worker.ler', 'profile.target_group.worker_ler')], default='any.vol', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any.vol', 'profile.target_group.any_vol'), ('any.ler', 'profile.target_group.any_ler'), ('refugee.vol', 'profile.target_group.refugee_vol'), ('refugee.ler', 'profile.target_group.refugee_ler'), ('student.vol', 'profile.target_group.student_vol'), ('student.ler', 'profile.target_group.student_ler'), ('worker.vol', 'profile.target_group.worker_vol'), ('worker.ler', 'profile.target_group.worker_ler')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='user_type',
            field=models.CharField(choices=[('learner', 'profile.user_type.learner'), ('volunteer', 'profile.user_type.volunteer')], default='learner', max_length=255),
        ),
        migrations.AlterField(
            model_name='state',
            name='matching_state',
            field=models.CharField(choices=[('idle', 'models.state.matching_state.idle'), ('searching', 'models.state.matching_state.searching')], default='idle', max_length=255),
        ),
    ]
