# Generated by Django 5.0.2 on 2024-05-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_alter_communityevent_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', 'profile.gender.any'), ('male', 'profile.gender.male'), ('female', 'profile.gender.female')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='gender',
            field=models.CharField(choices=[('any', 'profile.gender.any'), ('male', 'profile.gender.male'), ('female', 'profile.gender.female')], default=None, max_length=255, null=True),
        ),
    ]
