# Generated by Django 5.0.2 on 2024-05-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
