# Generated by Django 5.0.2 on 2024-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_communityevent_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'model.community_event.frequency.monthly'), ('weekly', 'model.community_event.frequency.weekly'), ('once', 'model.community_event.frequency.once')], default='once', max_length=255),
        ),
    ]
