# Generated by Django 5.0.2 on 2024-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_alter_communityevent_frequency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnconfirmedMatch',
            new_name='ProposedMatch',
        ),
    ]
