# Generated by Django 5.0.2 on 2024-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_rename_unconfirmedmatch_proposedmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='to_low_german_level',
            field=models.BooleanField(default=False),
        ),
    ]
