# Generated by Django 5.0.2 on 2024-06-19 14:24

import management.models.community_events
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_state_to_low_german_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='image',
            field=models.ImageField(blank=True, upload_to=management.models.community_events.PathRenameCommunityEvent('community_events_pics/')),
        ),
    ]
