# Generated by Django 5.0.2 on 2024-07-06 18:13

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_communityevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], max_length=1000),
        ),
    ]
