# Generated by Django 5.0.2 on 2024-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_alter_profile_target_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='partner_location',
            field=models.CharField(choices=[('anywhere', 'profile.partner_location.anywhere'), ('close', 'profile.partner_location.close'), ('far', 'profile.partner_location.far')], default='anywhere', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speech_medium',
            field=models.CharField(choices=[('any', 'profile.speech_medium.any'), ('video', 'profile.speech_medium.video'), ('phone', 'profile.speech_medium.phone')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_group',
            field=models.CharField(choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='partner_location',
            field=models.CharField(choices=[('anywhere', 'profile.partner_location.anywhere'), ('close', 'profile.partner_location.close'), ('far', 'profile.partner_location.far')], default='anywhere', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='speech_medium',
            field=models.CharField(choices=[('any', 'profile.speech_medium.any'), ('video', 'profile.speech_medium.video'), ('phone', 'profile.speech_medium.phone')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_group',
            field=models.CharField(choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], default='any', max_length=255),
        ),
    ]
