# Generated by Django 5.0.2 on 2024-07-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_alter_profile_partner_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lang_level',
        ),
        migrations.RemoveField(
            model_name='profileatmatchrequest',
            name='lang_level',
        ),
    ]
