# Generated by Django 5.0.2 on 2024-07-17 18:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_remove_profile_lang_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stillincontactform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='stillincontactform',
            name='user',
        ),
        migrations.AlterField(
            model_name='backendstate',
            name='slug',
            field=models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies'), ('db-filled-base-management-user-profile', 'Base Management User Profile'), ('db-created-default-score-source', 'Default Score Source Created'), ('pre-matching-call-active', 'Pre Matching Call Active'), ('updating-matching-scores', 'Updating Matching Scores')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_group',
            field=models.CharField(choices=[('any', 'profile.target_groups.any'), ('refugee', 'profile.target_groups.refugee'), ('student', 'profile.target_groups.student'), ('worker', 'profile.target_groups.worker')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.target_groups.any'), ('refugee', 'profile.target_groups.refugee'), ('student', 'profile.target_groups.student'), ('worker', 'profile.target_groups.worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_group',
            field=models.CharField(choices=[('any', 'profile.target_groups.any'), ('refugee', 'profile.target_groups.refugee'), ('student', 'profile.target_groups.student'), ('worker', 'profile.target_groups.worker')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileatmatchrequest',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.target_groups.any'), ('refugee', 'profile.target_groups.refugee'), ('student', 'profile.target_groups.student'), ('worker', 'profile.target_groups.worker')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users'), ('uncensored-admin-matcher', 'Is allowed to match users without censorship')], max_length=8000, null=True),
        ),
        migrations.DeleteModel(
            name='NoLoginForm',
        ),
        migrations.DeleteModel(
            name='StillInContactForm',
        ),
    ]
