# Generated by Django 5.0.2 on 2024-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='kind',
            field=models.CharField(choices=[('USER_BUCKET_IDS', 'User Bucket Ids'), ('MATCH_BUCKET_IDS', 'Match Bucket Ids')], default='USER_BUCKET_IDS', max_length=255),
        ),
    ]
