# Generated by Django 5.0.2 on 2024-08-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_statistic_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='unread_state_update_time',
        ),
    ]
