# Generated by Django 5.0.2 on 2024-08-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_remove_state_unread_state_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='unread_messages_state',
        ),
    ]
