# Generated by Django 5.0.2 on 2024-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_remove_state_unread_messages_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileAtMatchRequest',
        ),
    ]
