# Generated by Django 5.0.3 on 2024-09-03 11:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0075_delete_profileatmatchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='target_group',
            field=models.CharField(choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.target_group.any'), ('refugee', 'profile.target_group.refugee'), ('student', 'profile.target_group.student'), ('worker', 'profile.target_group.worker')], max_length=1000),
        ),
    ]
