# Generated by Django 5.0.3 on 2024-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_alter_profile_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='unsubscribed_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('any', 'profile.gender.any'), ('male', 'profile.gender.male'), ('female', 'profile.gender.female'), ('diverse', 'profile.gender.diverse')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_gender',
            field=models.CharField(choices=[('any', 'profile.partner_gender.any'), ('male', 'profile.partner_gender.male'), ('female', 'profile.partner_gender.female'), ('diverse', 'profile.partner_gender.diverse')], default='any', max_length=255),
        ),
    ]
