# Generated by Django 5.0.3 on 2024-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_alter_profile_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='unsubscribed_categories',
            field=models.JSONField(default=list),
        ),
    ]
