# Generated by Django 5.0.3 on 2024-11-26 16:47

import colorfield.fields
import management.helpers.path_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_emailsettings_unsubscribed_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the banner', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether the banner is currently active')),
                ('title', models.CharField(blank=True, help_text='Heading text', max_length=255)),
                ('text', models.TextField(blank=True, help_text='Main text content')),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('cta_1_url', models.TextField(blank=True, help_text='Cta 1 URL')),
                ('cta_1_text', models.CharField(blank=True, help_text='Cta 1 text', max_length=100)),
                ('cta_2_url', models.TextField(blank=True, help_text='Cta 2 URL')),
                ('cta_2_text', models.CharField(blank=True, help_text='Cta 2 text', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload landscape-oriented banner images with a 16:9 aspect ratio, minimum resolution of 1920 x 1080 pixels, and maximum file size of 2 MB. Use high-quality JPEG or PNG files, ensuring the image is sharp, clear, and allows for text overlay. Keep critical content centered to accommodate potential cropping across different devices.', upload_to=management.helpers.path_rename.PathRename('banner_pics/'))),
                ('image_alt', models.CharField(blank=True, help_text='Image alt text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='backendstate',
            name='slug',
            field=models.CharField(choices=[('db-created-default-cummunity-events', 'Default Community Events'), ('db-created-default-banners', 'Default Banners'), ('db-created-default-cookies-and-cookiegroups', 'Default Cookies'), ('db-filled-base-management-user-profile', 'Base Management User Profile'), ('db-created-default-score-source', 'Default Score Source Created'), ('pre-matching-call-active', 'Pre Matching Call Active'), ('updating-matching-scores', 'Updating Matching Scores')], max_length=255, unique=True),
        ),
    ]
