# Generated by Django 5.0.3 on 2024-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_emailsettings_unsubscribed_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='total_messages_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='total_mutal_video_calls_counter',
            field=models.IntegerField(default=0),
        ),
    ]
