# Generated by Django 5.0.3 on 2024-11-12 16:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_emailsettings_unsubscribed_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('any', 'profile.groups.any'), ('refugee', 'profile.groups.refugee'), ('student', 'profile.groups.student'), ('worker', 'profile.groups.worker'), ('other', 'profile.groups.other')], max_length=1000),
        ),
    ]
