# Generated by Django 5.0.3 on 2024-10-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_alter_profile_gender_alter_profile_partner_gender'),
        ('management', '0077_emailsettings_unsubscribed_categories'),
    ]

    operations = [
    ]
