# Generated by Django 5.0.3 on 2024-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_emailsettings_unsubscribed_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the banner', max_length=255)),
                ('active', models.BooleanField(default=True, help_text='Whether the banner is currently active')),
                ('title', models.CharField(blank=True, help_text='Heading text', max_length=255)),
                ('text', models.TextField(blank=True, help_text='Main text content')),
                ('cta_1_url', models.URLField(blank=True, help_text='Cta 1 URL')),
                ('cta_1_text', models.CharField(blank=True, help_text='Cta 1 text', max_length=100)),
                ('cta_2_url', models.URLField(blank=True, help_text='Cta 2 URL')),
                ('cta_2_text', models.CharField(blank=True, help_text='Cta 2 text', max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Image URL')),
                ('image_alt', models.CharField(blank=True, help_text='Image alt text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
