# Generated by Django 5.0.3 on 2024-12-02 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_banner_alter_backendstate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='latest_interaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='total_messages_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='total_mutal_video_calls_counter',
            field=models.IntegerField(default=0),
        ),
    ]
