# Generated by Django 5.0.3 on 2024-11-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_remove_profile_target_groups_profile_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='other_target_group',
            new_name='other_group',
        ),
    ]
