# Generated by Django 5.0.3 on 2024-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_banner_alter_backendstate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background',
            field=models.CharField(blank=True, help_text='Background color or image. Images can be set by the following: url(PATH_OF_IMAGE). Gradients can be set by the following: linear-gradient(#e66465, #9198e5).', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_1_url',
            field=models.CharField(blank=True, help_text='Cta 1 URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_2_url',
            field=models.CharField(blank=True, help_text='Cta 2 URL', max_length=255),
        ),
    ]
