# Generated by Django 5.0.3 on 2024-11-25 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_match_total_messages_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='latest_interaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
