# Generated by Django 5.0.3 on 2024-12-09 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_banner_background_alter_banner_cta_1_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='matching_state',
            new_name='searching_state',
        ),
        migrations.AddField(
            model_name='state',
            name='searching_state_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 15, 3, 26, 428669, tzinfo=datetime.timezone.utc)),
        ),
    ]
