# Generated by Django 5.0.3 on 2024-12-05 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_banner_background_alter_banner_cta_1_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='completed_off_plattform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='latest_interaction_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='total_messages_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='total_mutal_video_calls_counter',
            field=models.IntegerField(default=0),
        ),
    ]
