# Generated by Django 5.0.3 on 2024-12-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_match_completed_match_latest_interaction_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed_off_plattform',
            field=models.BooleanField(default=False),
        ),
    ]
