# Generated by Django 5.0.3 on 2024-12-05 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_banner_background_alter_banner_cta_1_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBroadcastList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='recipient_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
