# Generated by Django 5.0.3 on 2024-12-11 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_match_completed_match_completed_off_plattform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='matching_state',
            new_name='searching_state',
        ),
        migrations.AddField(
            model_name='state',
            name='searching_state_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 10, 29, 38, 681457, tzinfo=datetime.timezone.utc)),
        ),
    ]
