# Generated by Django 5.0.3 on 2024-12-09 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_rename_matching_state_state_searching_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='searching_state',
            field=models.CharField(choices=[('idle', 'models.state.searching_state.idle'), ('searching', 'models.state.searching_state.searching')], default='idle', max_length=255),
        ),
        migrations.AlterField(
            model_name='state',
            name='searching_state_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 9, 15, 5, 10, 297220, tzinfo=datetime.timezone.utc)),
        ),
    ]
