# Generated by Django 5.0.3 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_messagebroadcastlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebroadcastlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
