# Generated by Django 5.0.3 on 2025-01-07 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_alter_state_searching_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='searching_state_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DynamicUserList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='recipient_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
