# Generated by Django 5.0.3 on 2025-01-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0083_alter_state_searching_state_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
