# Generated by Django 5.0.3 on 2025-01-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0084_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedmatch',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedmatch',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposedmatch',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposedmatch',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
