# Generated by Django 5.0.3 on 2025-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_proposedmatch_expired_proposedmatch_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='small', max_length=255),
        ),
    ]
