# Generated by Django 5.0.3 on 2025-01-15 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0086_postcallreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcallreview',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
