# Generated by Django 5.0.3 on 2025-01-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0087_postcallreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='send_automatic_message_1week',
            field=models.BooleanField(default=True),
        ),
    ]
