# Generated by Django 5.0.3 on 2025-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_match_send_automatic_message_1week'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='activation_time',
            field=models.DateTimeField(blank=True, help_text='Activation time', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Expiration time', null=True),
        ),
    ]
