# Generated by Django 5.0.3 on 2025-02-10 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0089_banner_activation_time_banner_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='hash',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='notification.title', max_length=255),
        ),
    ]
