# Generated by Django 5.0.3 on 2025-02-18 15:44

import management.models.unconfirmed_matches
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0090_alter_notification_hash_alter_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedmatch',
            name='expires_at',
            field=models.DateTimeField(default=management.models.unconfirmed_matches.three_days_from_now),
        ),
        migrations.AlterField(
            model_name='proposedmatch',
            name='reminder_due_at',
            field=models.DateTimeField(default=management.models.unconfirmed_matches.one_day_from_now),
        ),
    ]
