# Generated by Django 5.0.3 on 2025-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_alter_proposedmatch_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
