# Generated by Django 5.0.3 on 2025-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_alter_proposedmatch_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmodel',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
