# Generated by Django 5.0.3 on 2025-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_alter_proposedmatch_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('unread', 'notification.state.unread'), ('read', 'notification.state.read'), ('archived', 'notification.state.archived'), ('deleted', 'notification.state.deleted')], default='unread', max_length=255),
        ),
    ]
