# Generated by Django 5.0.3 on 2025-03-25 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0093_shortlink_shortlinkclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
