# Generated by Django 5.0.3 on 2025-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0094_alter_shortlinkclick_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='filter_priority',
            field=models.IntegerField(default=0),
        ),
    ]
