# Generated by Django 5.0.3 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0095_banner_custom_filter_banner_filter_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
