# Generated by Django 5.0.3 on 2025-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlinkclick',
            name='source',
            field=models.TextField(default='none'),
        ),
    ]
