# Generated by Django 5.0.3 on 2025-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0098_shortlinkclick_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmodel',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
