# Generated by Django 5.0.3 on 2025-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_smsmodel_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('unread', 'notification.state.unread'), ('read', 'notification.state.read'), ('archived', 'notification.state.archived'), ('deleted', 'notification.state.deleted')], default='unread', max_length=255),
        ),
    ]
