# Generated by Django 5.0.3 on 2025-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_smsmodel_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematchingappointment',
            name='sms_task',
            field=models.TextField(default=''),
        ),
    ]
