# Generated by Django 5.0.3 on 2025-04-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0100_alter_notification_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematchingappointment',
            name='sms_task',
            field=models.TextField(default=''),
        ),
    ]
