# Generated by Django 5.0.3 on 2025-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0101_prematchingappointment_sms_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
