# Generated by Django 5.0.3 on 2025-04-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0102_profile_push_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_skill_description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
