# Generated by Django 5.0.3 on 2025-05-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0103_profile_job_search_profile_job_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_search',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
