# Generated by Django 5.0.3 on 2025-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0104_alter_profile_job_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='headline',
            field=models.CharField(blank=True, default='notification.headline', max_length=255),
        ),
    ]
