# Generated by Django 5.0.3 on 2025-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0105_notification_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityevent',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
