# Generated by Django 5.0.3 on 2025-05-23 12:28

import management.models.short_links
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0105_notification_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='tracking_cookies',
            field=models.JSONField(default=management.models.short_links._default_example_tracking_cookie),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='tracking_cookies_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
