# Generated by Django 5.0.3 on 2025-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0107_shortlink_tracking_cookies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
