# Generated by Django 5.0.3 on 2025-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_random_call_match',
            field=models.BooleanField(default=False),
        ),
    ]
