# Generated by Django 5.0.3 on 2025-07-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedmatch',
            name='deny_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
