# Generated by Django 5.0.3 on 2025-07-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_proposedmatch_deny_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'model.community_event.frequency.monthly'), ('weekly', 'model.community_event.frequency.weekly'), ('fortnightly', 'model.community_event.frequency.fortnightly'), ('once', 'model.community_event.frequency.once')], default='once', max_length=255),
        ),
    ]
