# Generated by Django 5.0.3 on 2025-07-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0110_alter_communityevent_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposedmatch',
            old_name='deny_reason',
            new_name='rejected_reason',
        ),
    ]
