# Generated by Django 5.0.3 on 2025-07-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0110_alter_communityevent_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_random_call_match',
            field=models.BooleanField(default=False),
        ),
    ]
