# Generated by Django 5.0.3 on 2025-09-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0113_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='register_at_app_root',
            field=models.BooleanField(default=False),
        ),
    ]
