# Generated by Django 5.0.3 on 2025-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0114_shortlink_register_at_app_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('learners_outside_germany', 'learners_outside_germany'), ('nrw_residents', 'nrw_residents'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('learners_outside_germany', 'learners_outside_germany'), ('nrw_residents', 'nrw_residents'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
