# Generated by Django 5.0.3 on 2025-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0115_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityevent',
            name='description',
            field=models.TextField(),
        ),
    ]
