# Generated by Django 5.0.3 on 2025-11-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_alter_communityevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='previous_management_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_14_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_3_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_7_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
