# Generated by Django 5.0.3 on 2025-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_state_previous_management_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='user_form_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_reminder_sent_number_days',
            field=models.IntegerField(default=0, help_text='Number of days between user form completed and last reminder sent'),
        ),
    ]
