# Generated by Django 5.0.3 on 2025-11-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_alter_communityevent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='previous_management_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]