# Generated by Django 5.0.3 on 2025-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_state_previous_management_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_last',
            field=models.IntegerField(default=0, help_text='Number of days between last interaction last reminder sent'),
        ),
    ]
