# Generated by Django 5.0.3 on 2025-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_state_previous_management_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='user_form_completed_14_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_3_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_7_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
