# Generated by Django 5.0.3 on 2025-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0117_match_interaction_reminder_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='interaction_reminder_last',
            field=models.IntegerField(default=0, help_text='Number of days between last interaction and last reminder sent.'),
        ),
    ]
