# Generated by Django 5.0.3 on 2025-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0117_state_previous_management_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_chat_interaction',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_last',
            field=models.IntegerField(default=0, help_text='Number of days between last interaction and last reminder sent.'),
        ),
        migrations.AddField(
            model_name='match',
            name='no_videocall_reminder_last',
            field=models.IntegerField(default=0, help_text='Number of days between first chat interaction and last reminder sent.'),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_14_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_3_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_7_days_reminder_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='user_form_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
