# Generated by Django 5.0.3 on 2025-11-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0118_state_user_form_completed_14_days_reminder_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_random_call_match',
            field=models.BooleanField(default=False),
        ),
    ]
