# Generated by Django 5.0.3 on 2025-12-11 09:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0119_match_is_random_call_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users'), ('uncensored-admin-matcher', 'Is allowed to match users without censorship'), ('use-beta-random-call', 'Is allowed to use the beta random call')], max_length=8000, null=True),
        ),
    ]
