# Generated by Django 5.0.3 on 2026-01-17 13:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_random_call_match',
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_14_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_2_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_7_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('use-autologin-api', 'Is allowed to use the auto login api (with a specific token)'), ('view-docs', 'Is allowed to view the docs'), ('view-email-templates', 'Is allowed to view the email templates'), ('view-stats', 'Is allowed to view the stats'), ('matching-user', 'Is allowed to match users'), ('uncensored-admin-matcher', 'Is allowed to match users without censorship')], max_length=8000, null=True),
        ),
    ]
