# Generated by Django 5.1.15 on 2026-01-15 01:47

import management.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to=management.models.profile.PathRename('profile_pics/')),
        ),
    ]
