# Generated by Django 5.0.3 on 2026-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_alter_state_extra_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_14_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_2_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_7_days_send',
            field=models.BooleanField(default=False),
        ),
    ]
