# Generated by Django 5.0.3 on 2026-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0121_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_14_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_2_days_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='interaction_reminder_7_days_send',
            field=models.BooleanField(default=False),
        ),
    ]
