# Generated by Django 5.0.3 on 2025-12-30 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0121_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpmessage',
            name='kind',
            field=models.CharField(choices=[('general', 'General'), ('technical', 'Technical'), ('report_user', 'Report User'), ('call_quality', 'Call Quality'), ('report_partner', 'Report Partner')], default='general', max_length=255),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='origin',
            field=models.CharField(blank=True, default='Contact Form', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='helpmessage',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_reported_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='helpmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
