# Generated by Django 5.0.3 on 2026-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_match_interaction_reminder_14_days_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='auto_email_m031_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_m032_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_m033_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_m042_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='first_interaction_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
