# Generated by Django 5.1.15 on 2026-01-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0123_match_interaction_reminder_14_days_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmessage',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
