# Generated by Django 5.1.15 on 2026-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0125_match_auto_email_m031_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='auto_email_u072_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_email_u073_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_email_u074_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_emails_u081_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_emails_u082_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_emails_u083_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='auto_emails_u084_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='onboarding_call_completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
