# Generated by Django 5.1.15 on 2026-01-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0126_state_auto_email_u072_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='has_received_first_match',
            field=models.BooleanField(default=False),
        ),
    ]
