# Generated by Django 5.1.15 on 2026-01-27 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0127_state_has_received_first_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='still_in_contact_form_access_token_user',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
