# Generated by Django 5.1.15 on 2026-01-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0128_state_still_in_contact_form_access_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed_off_plattform_auto_marked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
