# Generated by Django 5.1.15 on 2026-01-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0129_match_completed_off_plattform_auto_marked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='auto_marking_updated_logs',
            field=models.JSONField(default=list),
        ),
    ]
