# Generated by Django 5.1.15 on 2026-01-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0130_match_auto_marking_updated_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='user_journey_path',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='state',
            name='user_journey_path_last_updated',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
