# Generated by Django 5.1.15 on 2026-02-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0131_state_user_journey_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='force_match_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='has_match_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='user_journey_path',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
