# Generated by Django 5.1.15 on 2026-03-09 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0133_match_match_type_proposedmatch_match_type'),
        ('push_notifications', '0012_alter_apnsdevice_id_alter_gcmdevice_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('gcmdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.gcmdevice')),
                ('install_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique ID per installation on a mobile device', unique=True, verbose_name='Installation ID')),
                ('platform', models.CharField(blank=True, help_text='Platform of the device (iOS, android, ...)', max_length=256, null=True, verbose_name='Platform')),
                ('model_name', models.CharField(blank=True, help_text='The model of the device (iPhone 17 Pro, Google Pixel 10 Pro, ...)', max_length=256, null=True, verbose_name='Device model')),
            ],
            options={
                'verbose_name': 'Mobile device',
            },
            bases=('push_notifications.gcmdevice',),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='headline',
        ),
    ]
