# Generated by Django 5.1.15 on 2026-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0134_mobiledevice_remove_notification_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='last_not_attended_prematching_call_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='last_prematching_call_not_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='not_attended_auto_email_u053_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='not_attended_auto_email_u054_send',
            field=models.BooleanField(default=False),
        ),
    ]
