# Generated by Django 5.1.15 on 2026-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0135_state_last_not_attended_prematching_call_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='auto_email_m043_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_m044_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_m045_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='completed_10_video_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='completed_5_video_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='completed_8_video_calls',
            field=models.BooleanField(default=False),
        ),
    ]
