# Generated by Django 5.1.15 on 2026-03-28 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0136_match_auto_email_m043_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='latest_counter_sync',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
