# Generated by Django 5.1.15 on 2026-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0137_match_latest_counter_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='self_onbiarding_walkthrough_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_walkthrough_step_id',
            field=models.IntegerField(default=0),
        ),
    ]
