# Generated by Django 5.1.15 on 2026-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0137_match_latest_counter_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_completed_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_step_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
