# Generated by Django 5.1.15 on 2026-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0138_state_is_onboarded_state_self_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='self_onboarding_completed',
            new_name='self_onboarding_walkthrough_completed',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='self_onboarding_completed_at',
            new_name='self_onboarding_walkthrough_completed_at',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_onboarded',
        ),
        migrations.RemoveField(
            model_name='state',
            name='self_onboarding_step_id',
        ),
        migrations.AddField(
            model_name='state',
            name='self_onboarding_walkthrough_step_id',
            field=models.IntegerField(default=0),
        ),
    ]
