# Generated by Django 5.1.15 on 2026-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0138_state_is_onboarded_state_self_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='auto_email_fm021_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_email_fm022_send',
            field=models.BooleanField(default=False),
        ),
    ]
