# Generated by Django 5.1.15 on 2026-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0138_state_self_onbiarding_walkthrough_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='self_onboarding_walkthrough_completed_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
