# Generated by Django 5.1.15 on 2026-03-31 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0139_match_auto_email_fm021_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ghosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghosted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='is_ghosted_match',
            field=models.BooleanField(default=False),
        ),
    ]
