# Generated by Django 5.1.15 on 2026-03-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0139_state_self_onboarding_walkthrough_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='self_onbiarding_walkthrough_completed',
            new_name='self_onboarding_walkthrough_completed',
        ),
    ]
