# Generated by Django 5.1.15 on 2026-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0140_match_ghosted_by_match_is_ghosted_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='marked_as_ghosted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
