# Generated by Django 5.1.15 on 2026-03-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0141_match_marked_as_ghosted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='auto_email_m051_send',
            field=models.BooleanField(default=False),
        ),
    ]
