# Generated by Django 5.1.15 on 2026-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0142_match_auto_email_m051_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="attended_auto_email_u051_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="state",
            name="not_attended_auto_email_u052_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="state",
            name="attended_auto_email_u051_send_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="not_attended_auto_email_u052_send_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="not_attended_auto_email_u053_send_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="not_attended_auto_email_u054_send_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
