# Generated by Django 5.1.15 on 2026-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0143_state_u051_u052_and_u053_u054_send_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="last_prematching_checkoff_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
