# Generated by Django 5.1.15 on 2026-04-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0144_state_last_prematching_checkoff_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
