# Generated by Django 5.1.15 on 2026-04-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0145_state_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='deleted_full_user_data_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
