# Generated by Django 5.1.15 on 2026-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0146_state_deleted_full_user_data_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('learners_outside_germany', 'learners_outside_germany'), ('random_call_users', 'random_call_users'), ('match_eligible_users', 'match_eligible_users'), ('nrw_residents', 'nrw_residents'), ('none', 'None')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='communityevent',
            name='custom_filter',
            field=models.CharField(choices=[('capegemini', 'capegemini'), ('learners_with_a1a2', 'learners_with_a1a2'), ('learners_above_a1a2', 'learners_above_a1a2'), ('volunteers', 'volunteers'), ('learners', 'learners'), ('learners_outside_germany', 'learners_outside_germany'), ('random_call_users', 'random_call_users'), ('match_eligible_users', 'match_eligible_users'), ('nrw_residents', 'nrw_residents'), ('none', 'None')], default='none', max_length=255),
        ),
    ]
