# Generated by Django 5.1.15 on 2026-04-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0147_alter_banner_custom_filter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
