# Generated by Django 5.1.15 on 2026-05-04 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0150_user_django_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementAccessGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="management_accesses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "managed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="management_accesses_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="management_accesses_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["manager", "is_active"], name="mgmt_access_mgr_active_idx"),
                    models.Index(fields=["managed_user", "is_active"], name="mgmt_access_usr_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manager", "managed_user"),
                        name="unique_manager_managed_user_access",
                    )
                ],
            },
        ),
    ]
