# Generated by Django 5.1.15 on 2026-05-07 15:48

import management.models.unconfirmed_matches
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0151_managementaccessgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedmatch',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=management.models.unconfirmed_matches.three_days_from_now, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='extra_user_permissions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('view-api-schema', 'Is allowed to view API schemas'), ('view-database-schema', 'Is allowed to view database schemas'), ('matching-user', 'Is allowed to match users'), ('use-random-calls', 'Is allowed to use the random calls feature')], max_length=8000, null=True),
        ),
    ]
