# Generated by Django 5.1.15 on 2026-05-08 08:37

import management.models.unconfirmed_matches
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0151_managementaccessgrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='extra_user_permissions',
        ),
        migrations.AlterField(
            model_name='proposedmatch',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=management.models.unconfirmed_matches.three_days_from_now, null=True),
        ),
    ]
