# Generated by Django 5.1.15 on 2026-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0152_remove_state_extra_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='tag',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='tracking_cookies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
