# Generated by Django 5.1.15 on 2026-05-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0152_remove_state_extra_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'permissions': [('view_api_schema', 'Can view API schema'), ('view_database_schema', 'Can view database schema'), ('matching_user', 'Can perform matching operations'), ('use_random_calls', 'Can use random calls feature'), ('apply_management_permissions', 'Can apply management permissions')]},
        ),
    ]
