# Generated by Django 5.1.15 on 2026-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0154_supporttask_supporttaskaction_objecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
    ]
