# Generated by Django 5.1.15 on 2026-05-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0155_alter_state_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='attended_auto_email_u051_send',
            new_name='attended_auto_email_u071_send',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='attended_auto_email_u051_send_at',
            new_name='attended_auto_email_u071_send_at',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='not_attended_auto_email_u052_send',
            new_name='not_attended_auto_email_u051_send',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='not_attended_auto_email_u052_send_at',
            new_name='not_attended_auto_email_u051_send_at',
        ),
    ]
