# Generated by Django 5.1.15 on 2026-05-21 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0156_rename_attended_auto_email_u051_send_state_attended_auto_email_u071_send_and_more"),
        ("management", "0156_supporttask_supporttaskaction_objecthistory"),
    ]

    operations = []
