# Generated by Django 5.1.15 on 2026-05-26 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0156_rename_attended_auto_email_u051_send_state_attended_auto_email_u071_send_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(default=True, help_text='Show this course in public listings (e.g. the Trainings page). Disable for internal-only courses such as onboarding walkthroughs.')),
                ('available_to', models.CharField(choices=[('all', 'All'), ('learner', 'Learner'), ('volunteer', 'Volunteer')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField()),
                ('available_to', models.CharField(choices=[('all', 'All'), ('learner', 'Learner'), ('volunteer', 'Volunteer')], default='all', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.URLField()),
                ('video_title', models.CharField(blank=True, default='', max_length=255)),
                ('completed_title', models.CharField(blank=True, default='', max_length=255)),
                ('completed_description', models.TextField(blank=True, default='')),
                ('completed_additional_text', models.TextField(blank=True, default='')),
                ('completed_cta_label', models.CharField(blank=True, default='', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='management.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'chapter_id')},
            },
        ),
        migrations.CreateModel(
            name='ChapterQuizStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answers', models.JSONField(default=list, help_text='List of answer strings, e.g. ["Yes", "No", "Maybe"]')),
                ('correct_answer', models.CharField(max_length=512)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_steps', to='management.coursechapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_chapter_id', models.CharField(blank=True, default='', max_length=128)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='management.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
